### ISSUE TITLE
artTemplate 简洁语法怎么定义变量？

### ISSUE THREAD

**Issue by smithzhang010** [aui/art-template#120]
既然把var关键字给排除了，如果要临时使用一个变量，在简洁语法里怎么实现？

**Comment by latel** [comment]
虽然很纠结，但是我用  {{if j=0}}{{/if}} 来定义变量，呵呵

**Comment by aui** [comment]
没有提供定义变量的语法，如果需要定义需要自己修改源码并打包

**Comment by coogleyou** [comment]
简洁语法太坑了，我也遇到这个问题，开始以为像其他模板一样，最后写到一半了发现不能定义变量。。。情何以堪。。。建议简洁语法也把基本的功能加上去，要么就明确说明一下，避免在用到一半出现我这样的情况

**Comment by coogleyou** [comment]
@latel 我也只好这样用了

**Comment by diamont1001** [comment]
可以比较傻逼的使用以下语法，可以实现：var a = '123';的效果

`{{if a = "123" }} {{/if}}`
