### ISSUE TITLE
关于数组循环的问题

### ISSUE THREAD

**Issue by taolive** [aui/art-template#138]
var data1= ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他'];
怎么循环到模板中？一定要形如：var data1 = {name:['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']} 吗？

**Comment by alwaysYoungCohen** [comment]
文档还是太简陋，影响开发效率

**Comment by wudihzh** [comment]
文档还是太简陋，影响开发效率，这个循环的语法解释真是太糟糕了！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
