### ISSUE TITLE
简洁语法模式下如何使用for循环

### ISSUE THREAD

**Issue by John-Tang** [aui/art-template#154]
native模式可以使用如下语句

``` javascript
<%for (var i=0;i<10;i++) {%>
<!--blablabla-->
<%}%>
```

类似这种循环在简洁模式下，如何实现？

**Comment by coogleyou** [comment]
可以混合使用吗？如果不可以，我需要怎么修改才可以混合使用简洁语法和原生语法？

**Comment by miaojiangmin** [comment]
可以利用 index 来处理  {{if index=0}}{{/if}}

**Comment by kuangshp** [comment]
请问遍历对象貌似不能用简洁版的，只能用原生的吗

**Comment by kuangshp** [comment]
我想用简洁版去实现遍历对象，总是不能实现，求指点

**Comment by tianwenwen** [comment]
简洁版也可以遍历对象吧,例如
{{each}}
<span>name</span><span>$value.name</span>
<span>age</span><span>$value.age</span
{{/each}}

**Comment by statickid** [comment]
请问一下，模板，可以放到外置的js里吗，比如
	<script id="test" type="text/html" src="../js/art-temp.js"></script>
       这个外部的art-temp.js的代码就是：
<h1>{{title}}</h1>
		<ul>
		{{each list as value i}}
		<li>索引 {{i + 1}} ：{{value}}</li>
		{{/each}}
		</ul>

**Comment by statickid** [comment]
请问一下，模板，可以放到外置的js里吗，比如我新建了一个art-temp.js

这个外部的art-temp.js的代码内容就是模板：
 

    <ul>
    {{each list as value i}}
    <li>索引 {{i + 1}} ：{{value}}</li>
    {{/each}}
    </ul>

**Comment by EvanLiu2968** [comment]
{{if ticket_passenger.length>0}}
                {{each ticket_passenger as v i}}
                    {{if i!=0}
                        <span></span>
                    {{else }}
                        <span  class="active"></span>
                    {{/if}}
                {{/each}}
 {{/if}}
//我用简洁语法做判断除了{{ if isMulti }}这种，其他的都不行，看来只能用原生语法了

**Comment by vilenice** [comment]
我也遇到这个问题了，好坑啊

**Comment by nosee123** [comment]
下载地址有没有？
