### ISSUE TITLE
发现现在的helpers是共享的

### ISSUE THREAD

**Issue by pulo** [aui/art-template#156]
这样就有问题了
我模块A和模块B分别定义了一个同名helper，但执行内容不一样，结果就出现交叉错误了。
A和B相互都不知道双方定义了什么HELPER

**Comment by aui** [comment]
helper作为全局使用，应该统一来维护。这问题类似都在 window 上写方法一样，属于编码规范的问题

**Comment by pulo** [comment]
可在AMD模块内使用Template已经属于模块的私有变量了，为什么helper还会是全局的呢

**Comment by aui** [comment]
helper 就是为全局设计的，作用在整个 template 中，和 AMD 无关。如果非必要，可以在 data 中传入函数，能达到同样的目的
