### ISSUE TITLE
请问我代码里的template.compile为何不能正确编译？

### ISSUE THREAD

**Issue by hwoarangzk** [aui/art-template#170]
我用koa写了一个服务器，编译并展示模板部分的代码如下:

<pre>
template = require 'art-template'
module.exports = (next) ->
    console.log '--------render middleware starts-------------'
    data = @request.body
    console.log '---original html----'
    console.log @request.html
    console.log '---original data----'
    console.log data
    render = template.compile @request.html
    html = render data
    console.log '---compiled html----'
    console.log html
    @body = html
    yield next
</pre>

接下来是控制台的内容：

--------render middleware starts-------------
---original html----
<!doctype html>
<html>
<head></head>
<body>
        Hello index
        <%=name%>
</body>
</html>
---original data----
{
        "name": "test"
}
---compiled html----
<!doctype html>
<html>
<head></head>
<body>
        Hello index
        <%=name%>
</body>
</html>

原始的html字符串、数据、以及调用compile后的html都能在控制台里找到，整个过程没有报错。最后在浏览器里看到的页面中，`<%=name%>`是直接原样输出没有被编译成功的。这里为什么`<%=name%>`无法被正确编译呢？谢谢~

**Comment by hwoarangzk** [comment]
补充一下，又写了个简单的例子：
<pre>
template = require 'art-template'
str = 'the name is <%=name%>'
data =
	name: 'test'
render = template.compile str
console.log render(data)
</pre>
这里打印出来的结果，``<%=name%>``还是没有被正确编译出来而是原样输出了。请问是我哪里使用姿势不对么。。。

**Comment by hwoarangzk** [comment]
唔，上面两个问题是因为我用的版本是3.0.0,我还原成2.0.3就不会原样输出了。
但现在的问题是，如果我从本地读一个html文件，里面有``<%=name%>``，那么编译后，这个``<%=name%>``就直接被抹掉了，也不报错。如果我把本地的html文件全部copy，存到一个变量里，对这个变量进行编译，那么``<%=name%>``能正常编译出来。请问这是什么问题啊？我读本地html文件用的是`co-fs`模块，设置了'utf8'的

**Comment by aui** [comment]
3.0改动比较大，语法默认是简洁版本。具体细节可以看更新日志

**Comment by hwoarangzk** [comment]
嗯，我现在已经还原到2.0.3的版本了，没有原样输出，但是却被直接抹掉了一样，这是怎么回事啊。。。
