### ISSUE TITLE
看代码 render和compile是同一个函数哈？？

### ISSUE THREAD

**Issue by yanhaijing** [aui/art-template#171]
template.render = function (source, options) {
    return compile(source, options);
};

**Comment by valaxy** [comment]
+1 跟文档描述不一样

**Comment by aui** [comment]
render 返回是`String`，compile返回是`Function`

**Comment by aui** [comment]
render 返回是`String`，compile返回是`Function`

**Comment by aui** [comment]
>
>template.compile(source, options)
>将返回一个渲染函数。
>
>template.render(source, options)
>将返回渲染结果。
>

**Comment by valaxy** [comment]
可能是dist文件没有跟源码同步吧? 看这里:
https://github.com/aui/artTemplate/blob/master/dist/template-debug.js#L61-L63
其实我是这么来用这个render的:
```javascript
requirejs.config({
    paths: {
        'art-template'              : 'bower_components/artTemplate/dist/template-debug'
    }
})

var template = require('art-template')
var cmd = template.render(buildStr())({
	name                : file.get('name'),
	nameWithoutExtension: file.get('nameWithoutExtension')
})
```
看, 还是一个函数嘛

**Comment by aui** [comment]
@valaxy 使用`template.compile `吧，`template.render()` 确认有问题，下一版本改掉

**Comment by DavidKk** [comment]
问题+1 怎么不立即修复 我晕。。。。升级到3.0 立刻开始报错

**Comment by yanhaijing** [comment]
作者忙着写代码了o(∩_∩)o 哈哈
