### ISSUE TITLE
特殊字符有没有提供不转义的接口？

### ISSUE THREAD

**Issue by bo2337285** [aui/art-template#173]
如题。我想把标签写在对象里，然后在目标里以标签形式输出，结果很悲剧地给我把"<"转成"&lt"了……
p.s.用反斜杠也不行

**Comment by bo2337285** [comment]
找到了，在变量前加'#'就行，如{{#text}}

**Comment by zjzhome** [comment]
谢谢了，我也遇到了这个问题，一个#解决了
