### ISSUE TITLE
helper使用语法的一个问题

### ISSUE THREAD

**Issue by mycoin** [aui/art-template#174]
今天第一次使用ArtTemplate，离奇的发现：

```
{{authVO.name|truncate:12:'...'}}
```

尽然编译失败，好吧，我觉得肯定是语法不对，看了下源代码貌似应该这样：

```
{{authVO.name|truncate:12,'...'}}
```

嗯，还是不对？？好吧，我被深深的打败了，再看了一遍代码尽然要这样写：

```
{{authVO.name |truncate:12,'...'}}
```

好吧，第一次使用 ArtTemplate，个人感觉可以将语法规定的更加灵活些！

**Comment by aui** [comment]
抱歉，这里是一个很老的问题。artTemplate 使用正则来作简洁语法解析，而不是词法分析，导致这个问题无法根本避免。所以有这样的限制存在：辅助语法必须有空格，且不能在字符串中使用 "|"

我有计划使用词法分析的方式来重写 artTemplate简洁语法版，彻底规避此问题

**Comment by johnjackson** [comment]
至少在解决这个问题之前，应该在文档上明确说明。让人少走弯路

**Comment by aui** [comment]
已经解决
