### ISSUE TITLE
在浏览器段使用的时候，如果对象直接量换行了，整个模板就报错了

### ISSUE THREAD

**Issue by hwoarangzk** [aui/art-template#179]
<html>
...

<%
    var a = {
          name: 123
    };
%>
...
</html>

这样写的话直接报编译错误：
[template]:
anonymous

[name]:
Syntax Error

[message]:
Unexpected token =

如果我把a写为:

...
<%
    var a = {name: 123};
%>
...

这样就不会有错，help~谢谢~

**Comment by zquancai** [comment]
估计是合并成token时出问题了，原因是
```javascript
<%
var a = {
    name: 123
};
%>
```javascript
三行中有两行没有分号，应该是模板内部字符串解析的问题吧。其实模板也不要太复杂的功能。

**Comment by hwoarangzk** [comment]
嗯，在浏览器端确实遇到这个问题了，但是在服务器端却没有这个问题，不知道是什么具体的原因。我觉得对象直接量应该不算太复杂的功能吧。。。而且换行写是很正常的一个需求。。。
