### ISSUE TITLE
如果我在html模板里的js字符串中写了<%、%>，编译就报错了

### ISSUE THREAD

**Issue by hwoarangzk** [aui/art-template#197]
比如我的代码里有：

<pre>
<%
    var a = 'test <%';
%>
</pre>

那么在compile的时候就会报错。看了下源代码，是以openTag和closeTag来split提取js的，但是如果遇到以上这种情况应该怎么处理呢？

**Comment by noonhorse** [comment]
需要做转义吧， "<": "&#60;",  ">": "&#62;"

**Comment by noonhorse** [comment]
"&#60;
