### ISSUE TITLE
简洁语法中子模板如何使用父模板中的变量?请看详细内容

### ISSUE THREAD

**Issue by FengZeming** [aui/art-template#198]
main.html  
 -----  {{each $data}}         

```
           {{include './list' $value.list}}

      {{/each}}
```

list.html
----<ul>
    {{each $data}} {{include './content' $value}} {{/each}}
    <div class="clear-box"></div>
      </ul>
content.html
---id="{{$data.num}}{{$data.carID}}">

不能写html代码 我晕
尊敬的作者你好. 使用你开发的atrtemplate 预编译模式的文件实在是好用 只是目前觉得还是不太灵活
像上面的例子 我需要在content.html 中 使用 最main.html 中的 num变量 如何书写呢?
下面是我数据的片段

var data = [{
    title: '第一周（2015/03/16 — 2015/03/20）',
    num: 1,  <----我想再content.html 里使用这个变量
    list: [{
        carID: 1,
        cardNum: 55,
        cardURL: '../images/test2.png',
        cardName: '礼貌达人'
    }]

}]

**Comment by FengZeming** [comment]
是我描述不清楚?

**Comment by nyb869008813** [comment]
<script type="text/html" id="temp2">
			<div>
	    		<ul>
				{{each contents}}
				      <li>{{$value.content}}</li>
				{{/each}}            	
	            </ul>
	        </div>
		</script>
				  
		<script type="text/html" id="temp1">
		{{each list}}
		    <div>
		    	<h2>{{$value.title}}</h2>
		    	{{include 'temp2' $value.a}}
		    </div>
		{{/each}}
		</script>
		  
		 
		<script type="text/javascript">
			$(function(){
				
				  var data = {
				      list:[
					      {
					      		title:"这是一个测试标题1",
					      		a:{
					      			contents:[
							          	{"content":"这是一段内容1"},
							          	{"content":"这是一段内容1"},
							          	{"content":"这是一段内容1"}
						        	]
					      		}
					      },
					      {
					      		title:"这是一个测试标题2",
					      		a:{
					      			contents:[
						          		{"content":"这是一段内容2"},
						          		{"content":"这是一段内容2"},
						          		{"content":"这是一段内容2"}
						        	]
					      		}
					      }
				      ]
				  };
				  
				  var html = template('temp1', data);
				  $("#main").html(html);
				  
				
			});
		</script>


不知道这样的例子，是不是你想要的结果？

**Comment by nyb869008813** [comment]
<script type="text/html" id="temp2">
			<div>
	    		<ul>
				{{each contents}}
				      <li>{{$value.content}}</li>
				{{/each}}            	
	            </ul>
	        </div>
		</script>
				  
		<script type="text/html" id="temp1">
		{{each list}}
		    <div>
		    	<h2>{{$value.title}}</h2>
		    	{{include 'temp2' $value.a}}
		    </div>
		{{/each}}
		</script>
		  
		 
		<script type="text/javascript">
			$(function(){
				
				  var data = {
				      list:[
					      {
					      		title:"这是一个测试标题1",
					      		a:{
					      			contents:[
							          	{"content":"这是一段内容1"},
							          	{"content":"这是一段内容1"},
							          	{"content":"这是一段内容1"}
						        	]
					      		}
					      },
					      {
					      		title:"这是一个测试标题2",
					      		a:{
					      			contents:[
						          		{"content":"这是一段内容2"},
						          		{"content":"这是一段内容2"},
						          		{"content":"这是一段内容2"}
						        	]
					      		}
					      }
				      ]
				  };
				  
				  var html = template('temp1', data);
				  $("#main").html(html);
				  
				
			});
		</script>

看看上面的demo，是不是可以了？

**Comment by nyb869008813** [comment]
逗比版demo：

        <script type="text/html" id="temp2">
		<div>
	    		<ul>
				{{each}}
				      <li>{{$value.content}}</li>
				{{/each}}            	
	            </ul>
	        </div>
		</script>
				  
		<script type="text/html" id="temp1">
		{{each list}}
		    <div>
		    	<h2>{{$value.title}}</h2>
		    	{{include 'temp2' $value.contents}}
		    </div>
		{{/each}}
		</script>
		  
		 
		<script type="text/javascript">
			$(function(){
				
				  var data = {
				      list:[
					      {
					      		title:"这是一个测试标题1",
				      			contents:[
						          	{"content":"这是一段内容1"},
						          	{"content":"这是一段内容1"},
						          	{"content":"这是一段内容1"}
					        	]
					      },
					      {
					      		title:"这是一个测试标题2",
				      			contents:[
					          		{"content":"这是一段内容2"},
					          		{"content":"这是一段内容2"},
					          		{"content":"这是一段内容2"}
					        	]
					      		
					      }
				      ]
				  };
				  
				  var html = template('temp1', data);
				  $("#main").html(html);
				  
				
			});
		</script>

**Comment by zuibunan** [comment]
@ningyanbo temp2模板中如何引用temp1中$value.a本身？现在貌似只能拿到$value.a下一级的数据

**Comment by ningyanbo** [comment]
@zuibunan   $value.a  就是 contents
