### ISSUE TITLE
模板内部不支持原生js的方法？

### ISSUE THREAD

**Issue by MichaelGong** [aui/art-template#222]
我的模板中出现了：
<%
     parseInt(hasshakenum);
%>
结果报错：
Template Error
<filename>
resultPageTMP

<name>
Render Error

<message>
parseInt is not a function

<line>
22

<source>
parseInt(hasshakenum);

模板内部不支持原生js方法？请问怎么写才能支持？

**Comment by sorra** [comment]
试试(parseInt(hasshakenum))
另外，这里一定要parseInt吗，直接输出不好吗

**Comment by MichaelGong** [comment]
你好 ，你上面说的说的那个方式 我试过了 还是不行。
因为之前我用的其他的模板，习惯了在模板内部做逻辑处理，所以我在用artTemplate的时候 就自然的想和之前一样去处理，但是却发现类似于parseInt、JSON.stringify之类的方法无法在其中是用，就想了解一下，是插件不支持，还是我的用法有问题。

**Comment by Yuliang-Lee** [comment]
应该是artTemplate内部没有处理parseInt这个函数，看了下源码，应该是只处理以下：
```javascript
var KEYWORDS =
    // 关键字
    'break,case,catch,continue,debugger,default,delete,do,else,false'
    + ',finally,for,function,if,in,instanceof,new,null,return,switch,this'
    + ',throw,true,try,typeof,var,void,while,with'

    // 保留字
    + ',abstract,boolean,byte,char,class,const,double,enum,export,extends'
    + ',final,float,goto,implements,import,int,interface,long,native'
    + ',package,private,protected,public,short,static,super,synchronized'
    + ',throws,transient,volatile'

    // ECMA 5 - use strict
    + ',arguments,let,yield'

    + ',undefined';
```

**Comment by ierask** [comment]
好像是不支持,最好在渲染前处理,或者注册在help中,

**Comment by lgh06** [comment]
也遇到同样的问题，把要用的函数挂在模板数据里好像不好使啊……

**Comment by lgh06** [comment]
OK了。楼上说的2 3 都好使。

**Comment by jyjin** [comment]
@ierask  @Yuliang-Lee  简洁语法，需要逻辑判断一个自定义函数返回值，怎么做？如：判断某个参数的类型  {{if val | getValueType}} {{/if}}  template.helper('getValueType',function(){return 'int'})
类似这样的，不知道该怎么写，求大神，真的试的头都疼了...
