### ISSUE TITLE
刚发现了个 laytpl 号称比artTemplate更快的..有人尝试吗?

### ISSUE THREAD

**Issue by pkptzx** [aui/art-template#237]
刚发现了个 laytpl 号称比artTemplate更快的..有人尝试吗?
http://laytpl.layui.com/
我看都差不太多....

**Comment by aui** [comment]
很久没有登录 Github 了，在写一个比 artTemplate 更快的模板引擎还快的模板引擎，仅 353 字节：

```
function tpl (str) {
    return new Function("data", "_",
    "_='';_+=" + "'"
    + str.replace(/[\r\t\n]/g, " ")
       .replace(/'(?=[^%]*%>)/g,"\t")
       .split("'").join("\\'")
       .split("\t").join("'")
       .replace(/<%=(.+?)%>/g, "';_+=$1;_+='")
       .split("<%").join("';")
       .split("%>").join("_+='")
    + "'; return _;"
   );
}
```

![test](https://cloud.githubusercontent.com/assets/1791748/10993402/7e5cf470-84a9-11e5-8545-60d31bc0e644.png)

**Comment by pkptzx** [comment]
那什么时候放出来?我们把玩把玩

**Comment by miketwais** [comment]
这样一个就能称为模板引擎了啊？

在 2015-11-06 17:13:14，"糖饼" <notifications@github.com> 写道：


很久没有登录 Github 了，在写一个比 artTemplate 更快的模板引擎还快的模板引擎，仅 353 字节：

function tpl (str) {
    return new Function("data", "_",
    "_='';_+=" + "'"
    + str.replace(/[\r\t\n]/g, " ")
       .replace(/'(?=[^%]*%>)/g,"\t")
       .split("'").join("\\'")
       .split("\t").join("'")
       .replace(/<%=(.+?)%>/g, "';_+=$1;_+='")
       .split("<%").join("';")
       .split("%>").join("_+='")
    + "'; return _;"
   );
}

**Comment by aui** [comment]
@miketwais 那什么才是模板引擎？

**Comment by aui** [comment]
@pkptzx 二楼不是贴了源代码么？

**Comment by wangxingkai** [comment]
@aui 你这个槽吐得太冷，他们都没听懂…

**Comment by 1021683053** [comment]
哈哈，是太冷！

**Comment by yanhaijing** [comment]
要手写data前缀啊(/ □ \)

**Comment by jerryyan1990** [comment]
不明觉厉...

**Comment by jerryyan1990** [comment]
二楼的代码怎么用啊？没有文档吗？

**Comment by lfc625** [comment]
没看懂啊

**Comment by jerry-he** [comment]
不要迷恋速度，所谓模板引擎，就是把变量用自己定义的语法替换成js前台处理，模板处理的东西越少，自然性能越好，但是提供的脚手架就也少了很多

**Comment by yanhaijing** [comment]
@jerry-he 在乎速度的话 就是用预编译吧
