### ISSUE TITLE
关于include的传入参数 的两个小bug 

### ISSUE THREAD

**Issue by thesadabc** [aui/art-template#241]
### 环境
- express 4.13.3
- nodejs 4.2.1
- artTemplate 3.0
### include中最后多了个空格  导致渲染出错

如下面这个

```
{{include './common_toolbar' }}   // 最后面那个多了一空格
```

直接报错  后来查看一下log  发现被解析成了这个

```
include('./common_toolbar',)
```

希望文档中能说明一下 这个
### include直接传入对象  导致渲染出错

例子 因为对象中的空格也会被转成逗号  于是把空格都去掉了

```
{{include './common_toolbar' {toolbars:[{name:"登录",href:"/login"},{name:"注册",href:"/signup"}]}}}
```

这个被解析成了

```
include('./common_toolbar',{toolbars:[{name:"登录",href:"/login"},{name:"注册",href:"/signup"}]);
```

参数对象少了个括号  转义也不行   为了解决这个   我机智的采用了下面这个写法

```
{{include './common_toolbar' {toolbars:[{name:"登录",href:"/login"},{name:"注册",href:"/signup"}]} 0}}
```

在对象后面再加了一个参数  于是就能正确渲染了

**Comment by Leopold1988** [comment]
文档里include的传参写的有点简单，demo里include有例子但是没有传参的例子。
实际操作也遇到这个问题。
虽然楼主这个写法怪异，但问题解决了，不知是写法如此还是bug，希望作者关注一下，谢谢！

**Comment by zhang5171291** [comment]
正解， 的确 include xx 后面不能有空格
