### ISSUE TITLE
为啥获取不到名字为_id的值

### ISSUE THREAD

**Issue by PerttyZhan** [aui/art-template#242]
[ { _id: 56583421b4dc078c2c2603f5,
    houseconfig: 56583421b4dc078c2c2603f4,
    __v: 0,
    aptNum: '0',
    status: '2',
    recodeTime: '2015-11-27',
    scollUrl:
     [ '/image/56583421b4dc078c2c2603f5/QQ图片20151012103816.jpg',
       '/image/56583421b4dc078c2c2603f5/QQ图片20151012103847.png',
       '/image/56583421b4dc078c2c2603f5/QQ图片20151012103928.png',
       '' ],
    coverUrl: '/image/56583421b4dc078c2c2603f5/201541_licd01a_01_PH124898.jpg'
    area: '',
    address: '中国计量学院',
    require: [ '押一付三' ],
    des: [ '23楼', '电梯' ],
    price: '599',
    keywords: [ '富豪', '快乐' ],
    summary: '你值得拥有',
    title: '下沙富豪区',
    bh: 'xy001' } ]
我在模板里面
{{ each houses as value }}

```
                <div class="c3 thumbnail">
                    <a href="pc/detailMessage/{{value._id}}" class="thumbnail-body">
                        {{ if !!value.coverUrl }}
                            <img data-src="{{ value.coverUrl }}" width="" />
                        {{ else }}
                            <img data-src="image/default-curimg.png" width="" />
                        {{ /if }}

                        <div class="mask">
                            <div class="ma table">
                                <div class="table-cell">
                                    <h3 >{{ value._id }}</h3>
                                    <p >{{ value.summary }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

            {{ /each }}
```

但value._id获取不到

**Comment by yqz0203** [comment]
同问 id _id都取不到，后台不能，而浏览器使用可以。

**Comment by yqz0203** [comment]
貌似是mongoose model的问题。转成普通obj就行了。具体原因不明。
