### ISSUE TITLE
这个模板是否可以集成到knockout中？

### ISSUE THREAD

**Issue by yuqigong** [aui/art-template#254]
在模板中使用data-bind属性时，会解析错误。

**Comment by LuoPQ** [comment]
ko这种mvvm库本身就自带模板功能，而且更强大，根本不需要其他模板引擎了

**Comment by yuqigong** [comment]
确实是。但目前的项目希望可以替换成其他模版引擎（artTemplate）来代替内置的模版功能。
官网上也有例子，譬如：ko＋underscore。

**Comment by LuoPQ** [comment]
思路和underscore一样，定义一个自定义绑定，在绑定里使用artTemplate

**Comment by wuhuan** [comment]
artTemplate集成到ko后，在ko绑定的模板中使用artTemplate的语法，比如if语法会报错。
