### ISSUE TITLE
如何使用大于或者小于

### ISSUE THREAD

**Issue by suconghou** [aui/art-template#262]
if 条件判断的有很多局限性, 比较运算和&& , || , 等都没有给出说明如何使用,希望给出例子.

**Comment by javakf** [comment]
是哦，希望多给给出一些if的例子，比如判断元素是否存在，是否为空。貌似现在只有一个{{if admin}}的例子。

**Comment by iicanf** [comment]
&&  || 直接用就可以，{{if admin}} 难道不能判断是否为空？
