### ISSUE TITLE
使用3.0.0 版本 遇到布尔值如果不使用.toString()无法输出无论true或者false

### ISSUE THREAD

**Issue by jeff5665** [aui/art-template#270]
model={a:true}

html:
boolean:{{a}}

没输出true

demo可以参照:http://runjs.cn/detail/fphwh86n

**Comment by polandeme** [comment]
同样遇到，目前用０，１代替布尔值

**Comment by jeff5665** [comment]
我是{{a.toString()}} 方式处理布尔

**Comment by meitingshuoguo** [comment]
哎呀我今天也是，小白一个正愁不知道怎么解决呢，明天去公司试试。谢谢楼上了
