### ISSUE TITLE
简洁语法include 引入子模板的路径问题

### ISSUE THREAD

**Issue by lynnic26** [aui/art-template#271]
若我在主页面中使用{{include 'tpl/partial'}}引入tpl下的partial.html，
那tpl目录应该和主页面的html在同一级目录吗？然后partal应该是partial.html的名字吗？
我用了一下发现页面上只出现 {{include './tpl/partial'}} 这一串字符，并没有生效

**Comment by lmxin123** [comment]
我只在同一个页面中引用不同的模板

**Comment by LikeDege** [comment]
@lynnic26 根据路径引入子模板你能用吗？我怎么试都不行，到底支不支持？
