### ISSUE TITLE
对英文字符()和'的过滤问题

### ISSUE THREAD

**Issue by fanchangjifen** [aui/art-template#272]
参数中包含英文字符()和'是模板报错，模板本身对参数没有进行过滤，能否加上。
解决方法：参照bootstrapTable的效果，是否加个正则过滤，对含有特殊字符的参数进行过滤替换或者是直接忽略请求。。。
原谅我在这个全球最大的同性交友平台上面用中文。。。

**Comment by dan0314** [comment]
异性路过
