### ISSUE TITLE
table 模板解析报错

### ISSUE THREAD

**Issue by aqnghu** [aui/art-template#274]
=============================模板：
`
{{each OFFER_LIST as OFFER i}}
                    <div class="c_list c_list-line c_list-border">
                        <ul>
                            {{MAIN_OFFER = OFFER.MAIN_OFFER}}
                            <li class="link" ontap='pd.openOfferDetailPopup(this, {{MAIN_OFFER | stringify}});'>
                                <div class="pic">
                                    <span class="e_ico-pic-s e_ico-pic-r e_ico-pic-{{MAIN_OFFER.ACTION | actionTrans:2}}">
                                        {{MAIN_OFFER.ACTION | actionTrans:1}}
                                    </span>
                                </div>
                                <div class="main">
                                    <div class="title">
                                        <span class="e_red">[主商品]</span> 
                                        <span>{{MAIN_OFFER.OFFER_NAME}}</span>
                                    </div>
                                    <div class="content">{{MAIN_OFFER.VALID_DATE}}～{{MAIN_OFFER.EXPIRE_DATE}}</div>
                                    <div class="content">
                                        <table>
                                            {{each MAIN_OFFER.PRICES as PRICE k}}
                                            <tr><td>定价{{k+1}}：</td><td>{{PRICE.PRICE_NAME}}</td></tr>
                                            {{/each}}
                                        </table>
                                    </div>
`

=============================报错信息：

`
<filename>
offers_temp

<name>
Render Error

<message>
Cannot read property 'PRICE_NAME' of undefined

<line>
22

<source>

<table><tbody><tr><td>XX{{k+1}}：</td><td>{{PRICE.PRICE_NAME}}</td></tr></tbody></table>

`

**Comment by danyan** [comment]
@aqnghu  最后解决了吗，我也遇到了

**Comment by aui** [comment]
报错信息都给出来了，看不懂还是想找人翻译？

**Comment by danyan** [comment]
数据是存在的。

排查发现，template直接放在页面上的时候，浏览器会把模板语法挪到table上面，导致语法解析错误

正确做法，把template单独放在一个文件引入，或者在页面上存放的时候用 script标签包裹
