### ISSUE TITLE
如何使用简洁语法，给helper传递多个参数？

### ISSUE THREAD

**Issue by git-lt** [aui/art-template#280]
{{product.price.value | formatPrice: 'integer':'pms2':'pms3'}}  这样行不通，怎么办？

**Comment by bestao** [comment]
{{product.price.value | formatPrice: 'integer' pms2' 'pms3'}} 这里formatPrice有四个参数，第一个是value，其余三个是后面三个

**Comment by johnjackson** [comment]
{{$value.uname | str_star : 1  '***'}} 
我这样写，还是报错，求正解？

**Comment by johnjackson** [comment]
我看到另一个问题中提到help不支持多个空格，也不支持首尾空格

**Comment by johnjackson** [comment]
我自己瞎试，居然解决了：
{{$value.uname | str_star : 1,'***'}}

**Comment by KarlStony** [comment]
{{value | methodName: 'argument1',‘argument2','argument3'}}
