### ISSUE TITLE
是否支持对象循环遍历

### ISSUE THREAD

**Issue by yatelu1** [aui/art-template#283]
是否支持这种循环？
`{
  props: {
    power: '150 hp',
    speed: '200 km/h',
  }
}`

**Comment by RosApr** [comment]
支持啊，你的对象外层也是数组么

**Comment by longfeidong** [comment]
如果想拿到props这个键应该怎么写？不是键值，要键，就是直接取到props这个字符串能不能取到？

**Comment by RosApr** [comment]
如果loop的是array 则 @value.index为 当前下标，如果循环的是object 的attr 则 @value.index为 key-value 中的key。
把你的数据贴上来看看。
