### ISSUE TITLE
template如何从外部引入

### ISSUE THREAD

**Issue by li164902697** [aui/art-template#291]
<script id="entry-template" type="text/html"></script>

如何把这个模板从HTML中剥离出来，通过文件引入进来

**Comment by xuecrown** [comment]
找到方法了么同求~~

**Comment by xuecrown** [comment]
现有的用js拼接模板太难维护了

**Comment by Anikinly** [comment]
@li164902697

**Comment by Anikinly** [comment]
@xuecrown

**Comment by Anikinly** [comment]
@wangxiao

**Comment by wangxiao** [comment]
README 里面就有吧 https://github.com/aui/artTemplate#使用预编译
