### ISSUE TITLE
什么时候能开发一个webpack的loader呢

### ISSUE THREAD

**Issue by lifeforfun** [aui/art-template#295]
目前项目使用的是arttemplate引擎，但想将项目通过webpack打包却发现没有arttemplate的loader，使用其他的template loader虽然可以加载单个模板为字符串再通过arttemplate编译，但是模板里无法使用include语法，希望官方能开发一款支持webpack的loader

**Comment by byends** [comment]
我写好了，客官，请慢用 https://github.com/byends/art-template-loader

**Comment by renhlin** [comment]
你这个都只支持简洁语法，不支持原生语法

**Comment by byends** [comment]
@renhlin 支持哦，webpack 配置 loader 时，传相应的 option 进去

**Comment by aui** [comment]
<https://github.com/aui/art-template-loader>

art-template 已经发布官方 loader，支持 art-template@4 所有的功能，包括子模板与模板继承功能。

特别感谢 @byends 转让 npm 包名～

**Comment by fantasy525** [comment]
兄弟你有使用这个loader的demo吗？我想学习下，我自己实现的发现它没办法实现在本地输出渲染好html文件？是我使用方法不对吗？

**Comment by lifeforfun** [comment]
@fantasy525 和其他的loader用法一致，我这里是把模板文件命名为tmpl后缀以区分普通html文件，然后webpack配置loader
```
{
     test:/\.tmpl$/,
     use:['tmodjs-loader'],
}
```

**Comment by zp-nines** [comment]
我使用.html文件作为模版文件，但是构建的时候速度非常的慢。是模版文件的问题么？还是我使用的方式不正确
`{
    test: /src\/.*\.html$/,
   loader: "art-template-loader",
}`
