### ISSUE TITLE
嵌套模板后幻灯与tab标签js失效

### ISSUE THREAD

**Issue by Realybig** [aui/art-template#297]
页面含有幻灯片与tab标签js，将页面嵌套进模板后失效，怀疑是页面加载过程中幻灯与tab标签js检测到页面html代码没有相应代码从而没有执行(代码在模板内部)，理论上是否先执行模板填充然后在执行幻灯与tab标签js就好用了呢？数据来源是json文件，请问我应该如何操作？

**Comment by aui** [comment]
你的问题是什么？

**Comment by mioo** [comment]
模板渲染完成后需要重新绑定事件
