### ISSUE TITLE
是否有内置方法判断模板渲染加载资源完成？

### ISSUE THREAD

**Issue by ouzhou** [aui/art-template#298]
不知道是不是我使用姿势不正确，我将结果用jqeury append到dom节点里面，里面的html标签有img的会去加载资源文件，我要怎么去判断这些资源文件加载完成啊？之前可用img.onload来判断，现在暂时只能写一个定时器不断读取图片高度。补充一下，之前有用jqeury $(xx).load试过，但是好像没有效果

**Comment by aui** [comment]
http://mp.weixin.qq.com/s/yuiq4I4UKL2XBjE7SbduCQ
