### ISSUE TITLE
传递给模板的是一个二维数组，在模板内怎么读取第二维的元素内容

### ISSUE THREAD

**Issue by notinmood** [aui/art-template#307]
比如，我的二维数组这这样，
{
            "id" => "82"
            "remark" => 'hello',
            "time" => "2016-06-15 15:23:21",
            "contact" =>
                {
                    "id" => "182",
                    "name" => "解然",
                    "phone" => "18888888888",
                }
        }

到模板里面的时候，想访问contact子属性phone，
如下写法总是不对：{{value.contact.phone}}，这个需要怎么写呢？

**Comment by aui** [comment]
js 可以通过 [index] 的方式获取到数组下标，例如：data[3][0].value
