### ISSUE TITLE
双花括号嵌套时 编译出错

### ISSUE THREAD

**Issue by soonyh** [aui/art-template#313]
bug 预览 ： http://runjs.cn/code/g41s4yr5 

描述：

下面的data字段的值是一个对象，下列写法解析出错，是不是在编译false右侧的‘}}’时 出错了？

 &lt;a href="javascript:;" onclick="App.modal({width:'container',data:{settlementId:{{settlementRuleId}},editable:false}})"&gt;{{settlementRuleId}}&lt;/a&gt;

**Comment by lqixv** [comment]
artTemplate 支持改掉双花括号的，你改用别的就可以了
