### ISSUE TITLE
条件判断的时候无法使用if else

### ISSUE THREAD

**Issue by hlshang** [aui/art-template#318]
如题，我如下使用：
{{if 0==0}}
0
{{else if}}
1
{{/if}}

报错Template Error

**Comment by leixu2txtek** [comment]
else if 应该添加条件，如果没有条件 使用 else

**Comment by ChenJiaH** [comment]
在Node环境下，使用该模板，已经直接输出userData.showType测试，数据没问题
``` Javascript
    {{if userData.showType == "pinterest-img"}}
    0
    {{else if userData.showType == "regular"}}
    1
    {{else}}
    2
    {{/if}}
```

报错Template Error

同样的语法在tmod里面使用，没有问题
