### ISSUE TITLE
有关文档的一点建议

### ISSUE THREAD

**Issue by mosquito1994** [aui/art-template#333]
artTemplate支持两种语法，然后分别的简单示例过后，有一个`查看语法与演示`，这一开始让我认为只是演示内容而并没有找到模板语法的入口，推荐在`简洁语法``原生语法`标题后面直接给一个入口，比较清晰。

另外，看到14年就有人在提的一个issue，也是十分希望添加extend功能。我十分喜欢jade(pug)的include和extend功能，但是由于jade在浏览器端表现不佳，在node和浏览器端需要共享模板的情况下选择了相对优秀的artTemplate，如果有extend功能也会使artTemplate更加完美。

**Comment by aui** [comment]
正在考虑实现 extend 中

**Comment by aui** [comment]
已经支持布局
