### ISSUE TITLE
文档写的太简洁了吧

### ISSUE THREAD

**Issue by travelk** [aui/art-template#336]
很多用法都是自己摸索出来或者看别人的才知道...

**Comment by RosApr** [comment]
同感。。。摸索中补全api

**Comment by Riant** [comment]
看 /doc/ 文件夹，还算基本全面吧。https://github.com/aui/artTemplate/tree/master/doc

**Comment by jhd124** [comment]
没错，在号称性能卓越的项目里，这文档写得也是没谁了

**Comment by aui** [comment]
感谢各位的建议，4.0.0 文档不再拆开
