### ISSUE TITLE
能不能取JSON对象里的key呢？

### ISSUE THREAD

**Issue by longfeidong** [aui/art-template#340]
{
    "28" : [……]
}
假如我需要拿到28这个key，我在模板里应该怎么写呢？js里可以for…in，但模板中貌似不行吧！

**Comment by nuintun** [comment]
$data[28]

**Comment by CntChen** [comment]
用 `each` 就可以了：
```
{{each list}}
    <li>{{$index}} - {{$value.user}}</li>
{{/each}}
```
其中的`$index`就是key。

因为源码对`each`的实现就是支持 Array 和 Object 的，对 Object 也是使用 `for...in`:
https://github.com/aui/artTemplate/blob/master/src/utils.js#L44

**Comment by jiaxf** [comment]
Object对象  $index就是key , $value就是 value值
