### ISSUE TITLE
关键字之间只能为1个空格，否则报错

### ISSUE THREAD

**Issue by 1301469062** [aui/art-template#344]
each  object as value   前面关键字之间只能为1个空格，否则报错，试验了另一个模板引擎没有类似问题，感觉这个问题很无厘头，没道理，希望官方能够解决(    刚刚查看到这个问题14年就有人提出了，现在16年底了还没解决，这是腾讯的框架吗？？？？？？？？？？？？？)

**Comment by longfeidong** [comment]
这个已经不维护了，少敲一个呗

**Comment by 1301469062** [comment]
期望他可以维护下去，不是腾讯的吗？就这么放弃了多可惜，还有一大票用户

**Comment by latel** [comment]
不来就是评职称用的，你们想多了

**Comment by aui** [comment]
已经停止维护很多年了，不过最近将它重构了一下，你提到的问题已经彻底解决
