### ISSUE TITLE
express上使用arttemplate，是否支持layout功能？

### ISSUE THREAD

**Issue by Janking** [aui/art-template#345]
如题：

**Comment by hstarorg** [comment]
可以考虑自己扩展，我自己扩展了一个，但不太好用。

**Comment by aui** [comment]
`include(file, data)` 的第二个参数可以传入数据，是否可以代替 layout 的功能了？

**Comment by hstarorg** [comment]
@aui 性质不太一样哇。include需要每个页面引入。layout是被N多页面引入。我用不好的方式简单实现了一下layout：https://github.com/HstarStudio/art-template-plus

**Comment by aui** [comment]
v4.1.0 已经支持 Layout

**Comment by hstarorg** [comment]
@aui 大赞~我那个残次品可以干掉了。
