### ISSUE TITLE
3.0.3 to 3.1.0 不兼容

### ISSUE THREAD

**Issue by ekoneko** [aui/art-template#348]
新版本.render()方法直接返回字符串类型, 而非原先的 function

 npm --save 直接安装package.json 里的依赖基本上都是 "art-template": "`^`3.0.3",

这种不兼容的接口变更不应该定义为4.0.0么

莫名其妙因为前同事选的模板踩了一个坑...

**Comment by aui** [comment]
抱歉，实际上这个是个大 BUG …
