### ISSUE TITLE
 骗了一波赞，然后就变成垃圾项目了？

### ISSUE THREAD

**Issue by DemonCloud** [aui/art-template#351]

**Comment by andrew-qiu** [comment]
严重同意，国内开源项目要不就是垃圾多，要不就是还可以的就不维护了

**Comment by Huang-Libo** [comment]
传说中的僵尸项目.

**Comment by aui** [comment]
抱歉，考虑前端技术日新月异，前端模板引擎使用场景很少了，所以我太多动力在这个项目上继续投入。

最近 art-template 规划找到了新的方向，可以关注 v4.0.0 开发进度 <https://github.com/aui/art-template/tree/4.0.0>

**Comment by latel** [comment]
新方向是啥方向
