### ISSUE TITLE
在锚点的href属性中使用模版语法震惊的发现有一个无法跳转，也不报错

### ISSUE THREAD

**Issue by piecefly** [aui/art-template#359]
![image](https://cloud.githubusercontent.com/assets/8073355/23832556/884fd05a-0771-11e7-955d-83d831cbf695.png)
标签中跳转引用到的json内容的截图如上，现在的问题就是点击后不跳转了，也不报错，但是href值换成其他的就可以

**Comment by aui** [comment]
<http://mp.weixin.qq.com/s/yuiq4I4UKL2XBjE7SbduCQ>
