### ISSUE TITLE
模版是不是不支持IE8？希望解决

### ISSUE THREAD

**Issue by dingyanhe** [aui/art-template#360]
代码网址是：http://dingyanhe.blog.163.com/blog/static/26175304020172291051697/
使用template函数 IE8报错（模版错误），使用complie函数IE8不报错也不输出内容。谷歌和IE9、IE9+都不报错

**Comment by aui** [comment]
<http://mp.weixin.qq.com/s/yuiq4I4UKL2XBjE7SbduCQ>
