### ISSUE TITLE
openTag和CloseTag不匹配会缺失东西

### ISSUE THREAD

**Issue by ekea0407** [aui/art-template#363]
template.compile('<div>{"key1" : {"subkey1" : {{test}}  }}</div>')
最后一个}}后面的东西丢失

    forEach(source.split(openTag), function (code) {
        code = code.split(closeTag);
        
        var $0 = code[0];
        var $1 = code[1];

        //fixed
        if(code.length > 2){
            code.shift();
            $1 = code.join(closeTag);
        }
......

**Comment by aui** [comment]
需要避免代码与模板结束符匹配，写法上得特别注意下
