### ISSUE TITLE
each嵌套时，子循环引用变量解析错误

### ISSUE THREAD

**Issue by fdxmslx** [aui/art-template#365]
var data = {
    list: [{
    	list: ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']
    }, {
    	list: ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']
    }, {
    	list: ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']
    }]
};

{{each list value i}}
{{each value.list val}}
{{val}}
{{/each}}
{{/each}}

多层循化时会出现变量解析错误，如上代码。解析错误见图

![qq 20170414135914](https://cloud.githubusercontent.com/assets/27476479/25034655/957b75d2-211a-11e7-994b-120b659a3ef3.jpg)

**Comment by aui** [comment]
4.0.0-bate1 已经修复
