### ISSUE TITLE
使用require.js加载template.js报错

### ISSUE THREAD

**Issue by ayiui4566** [aui/art-template#366]
发现template.js也有require语句，这个怎么解决啊？

**Comment by ayiui4566** [comment]
我只想前端用这个，用不到fs模块啊

**Comment by aui** [comment]
在 requirejs 配置中设置一个别名试试？文档我会再更新

**Comment by aui** [comment]
已经更新版本，提供了 web 版本文件。

文档：

<https://github.com/aui/art-template#web>

requirejs 加载范例：

<https://github.com/aui/art-template/blob/master/example/requirejs/index.html>

**Comment by ayiui4566** [comment]
好快，多谢啊，头腾了一早上这个问题哈
