### ISSUE TITLE
arttemplate怎么引入其他目录的模板，在浏览器上

### ISSUE THREAD

**Issue by hankanon** [aui/art-template#367]
我想在main.html页面中引入header.html中的模板，header.html中的页面内容怎么写，main.html中怎么引入，看到介绍是{{include "header.html" $data}}，但是报错，错误如下：
刚开始接触这个模板，还不知道怎么解决，希望能给解决下。
template.js:2 Template Error

<filename>
header.html

<name>
Render Error

<message>
Template not found

**Comment by ayiui4566** [comment]
悲剧啊，我已经换jucier了啊。

**Comment by ayiui4566** [comment]
requre.js都引用不了，悲催啊

**Comment by aui** [comment]
浏览器没有文件加载能力，可以考虑 webpack loader <https://github.com/aui/art-template-loader>
