### ISSUE TITLE
用在移动端浏览器的，请问我该去哪里找哪个js来下载啊？是lib/template-web.js吗？

### ISSUE THREAD

**Issue by YYmmlin** [aui/art-template#374]
是用在移动端浏览器的，请问我该去哪里找哪个js来下载啊？是lib/template-web.js吗？
template-web.js不是说6Kb吗？怎么是14多Kb?  
怎么没有dist文件夹？我也没找到6KB的js文件啊？

可以解答一下吗？

**Comment by aui** [comment]
gzip 6kb
