### ISSUE TITLE
4.5.0版本自定义界定符

### ISSUE THREAD

**Issue by CarNightGun** [aui/art-template#389]
4.5.0版本下的example下的web-native-syntax里的tag.xml的示例直接用浏览器打开没有效果啊。
请问这个版本还支持自定义界定符吗？

**Comment by aui** [comment]
tag.html 已经过期，我已经删掉了。请设定 `template.defaults.rules[0].test` 来设定语法的匹配正则。默认配置如下：

<https://github.com/aui/art-template/blob/master/src/compile/adapter/rule.native.js#L2>
