### ISSUE TITLE
node版本和web版本的语法界定符冲突

### ISSUE THREAD

**Issue by theoldmoon** [aui/art-template#395]
我用art-template-loader 的webpack loader加载器去打包渲染html，然后我在这个html里又有一个script标签，标签里还存放着我需要异步渲染的模版html，然后界定符冲突，node端的渲染已经把script标签里的模版给渲染了，导致script标签里的模版失效。

后 main我又去看了下node版的art-template，发现没有提供修改rules的方法，我用加载器里的options的rules传了一个规则数组。发现会覆盖use方法，node端有没有类似web端的template.defaults.rules[0].test=xxxx 的方法呢？

**Comment by aui** [comment]
你要解决的其实就是你说的问题：“我用加载器里的options的rules传了一个规则数组。发现会覆盖use方法”——options 会覆默认配置，数组也一样，所以这种情况是预期之内的。

你可以先复制默认配置的 rules，修改后扔给 loader 的 options 解决问题

**Comment by theoldmoon** [comment]
考虑到的是 如果你的art-template node 版本更新或者迭代了，use方法内容变了，我们还要去维护，比较不合理，希望能在下个版本的art template 看到复写node版本的rules 而不动用use方法。

**Comment by aui** [comment]
你只需要改动界定符，不会影响 use 方法：

```js
var rule = template.defaults.rules[0];
rule.test = new RegExp(rules.test.source.replace('<%', '{%').replace('%>', '%}'));
```

**Comment by theoldmoon** [comment]
web版我知道如何改动，但是在node版中，是通过webpack loader加载器去调用的，不能拿到template变量，无法通过defaults来修改。

**Comment by theoldmoon** [comment]
而且我发现，在webpack 加载器loader 引用 art template loader 并且配置了options的rules，复制原来默认配置的rules 并且覆盖，只改变test的正则表达式，会发生错误，若在art-template-node.js 中去修改test，则不会发生错误，观察了下源代码，是不是你自己封装的$extend的方法有问题？

**Comment by theoldmoon** [comment]
目前只能在你的源代码中，把artRule 这个编号12模块的test 修改掉了。

**Comment by theoldmoon** [comment]
问题已解决，少了个内部splite方法没有copy

**Comment by aui** [comment]
webpack loader 依赖的是你项目自身的 art-template 版本，所以你可以直接 `require('art-template')` 来修改默认配置
