### ISSUE TITLE
TemplateError 在ie内核浏览器和一些移动端上

### ISSUE THREAD

**Issue by ShineMy** [aui/art-template#396]
在chrome下显示正常，
在ie内核和一部分手机上显示{ Template Error }，

在ie下报错如下：
TemplateError {
    "name": "RuntimeError",
    "path": "activeTmpl",
    "message": "缺少对象",
    "line": 139,
    "column": 131,
    "source": "{{[value.Type,value.SubType] | typeRender}}"
}

数据源如下：
[
    {
      "ID": "40350003",
      "Type": "3",
      "SubType": "3",
      "Rank": "5",
      "Name": "祈愿塔罗牌",
      "Icon": "Item00_019",
      "Num": 5
    },
    {
      "ID": "",
      "Type": "99",
      "SubType": "",
      "Rank": "",
      "Name": "",
      "Icon": "",
      "Num": 300
    }
  ]

请问这是什么原因？

**Comment by aui** [comment]
能否给全信息，这样我完全无法调试？template 的版本、浏览器版本、可重现的代码等（务必过滤掉无关代码）。问题我先关闭，符合要求后重新打开。

**Comment by ShineMy** [comment]
**问题：在chrome下显示正常，在ie内核和一部分手机上显示{ Template Error }**
template版本：4.8.0
浏览器版本：ie 11
错误提示：

**SCRIPT1010: 缺少标识符
test.html (38,57)**

**TemplateError {
    "name": "RuntimeError",
    "path": "activeTmpl",
    "message": "缺少对象",
    "line": 9,
    "column": 115,
    "source": "{{[val.Type,val.SubType] | typeRender}}"
}**

重现代码Demo：
html:
```
    <div class="activeGroup">
        <script id="activeTmpl" type="text/html">
            {{each ParticipationReward val index}}
                <img class="iconBg" src="http://webshuiqinling.ufile.ucloud.com.cn/activeIcon/{{[val.Type,val.SubType] | typeRender}}.png" alt="">
            {{/each}}
        </script>
    </div>
    <script type="text/javascript">
        template.defaults.imports.typeRender = function([Type,SubType]){
            if(Type == 13 || Type == 99){
                return 'otherIconBg';
            }
            else{
                if(SubType == 1 || SubType == 2){
                    return 'iconBg';
                }
                else if(SubType == 3 || SubType == 9){
                    return 'otherIconBg';
                }
            }
        };
    </script>
```
js:
```
var html = template('activeTmpl',{
      "ParticipationReward": [
        {
          "ID": "40350003",
          "Type": "3",
          "SubType": "3",
          "Rank": "5",
          "Name": "祈愿塔罗牌",
          "Icon": "Item00_019",
          "Num": 5
        }
      ]
    });
    $('.activeGroup').html(html);
```

**Comment by aui** [comment]
你这个问题是因为你的 `template.defaults.imports.typeRender`使用了 ES6，存在浏览器兼容问题

**Comment by ShineMy** [comment]
原来如此，请问应该如何解决？抱歉我没有解决思路。。
另外，我这里用的是文档中的标准写法，但是文档中写道兼容ie8+，实际ie8+还是存在不兼容。

**Comment by aui** [comment]
你的问题和模板引擎没有任何关系，是浏览器不支持你写的自定义函数

**Comment by ShineMy** [comment]
还烦请您提示下我这种情况如何解决呢？

**Comment by aui** [comment]
```js
function(args){
var Type = args[0], SubType = args[1];
```
