### ISSUE TITLE
在express中使用，视图文件扩展名可以改成.html吗

### ISSUE THREAD

**Issue by aofong** [aui/art-template#399]
配置extname貌似不行，默认的.art扩展名在vscode中没有语法高亮及其他支持不方便
```
// view engine setup
app.engine('art', template);
app.set('view options', {
    extname: '.html'
});
```

**Comment by aui** [comment]
1. extname 的用途：如果引入的模板没有后缀名，模板引擎会自动添加 extname 来查找模板文件
2. vscode 的语法高亮在计划中

**Comment by aofong** [comment]
@aui 谢谢，继续是3.0版本，4.0版本的layout很棒

**Comment by i5ting** [comment]
@aui vscode的语法高亮在计划中尽快啊，非常需要，贡献代码也可以
