### ISSUE TITLE
有层级的数据我想递归输出结构

### ISSUE THREAD

**Issue by scgy5555** [aui/art-template#40]
需求是无限层级的列表功能，数据是一层嵌套一层
但是突然想不到怎么在模板里实现递归操作
编译后的代码也不知道怎么编译

有什么比较好的实现方案么？

**Comment by IEfucker** [comment]
两个each不是双重循环吗

搜到了这个语法更清晰，是后来的版本支持吧
`
<script type="text/html" id="list1">

    <div style="padding:10px;">
        <div id="id_{{id}}">
            <span>{{title}}</span>
            <span>{{content}}</span>
            {{if children.length>0}}

            {{each children as node2}}
            {{include 'list1' node2}}
            {{/each}}

            {{/if}}
        </div>
    </div>

</script>
`
