### ISSUE TITLE
include使用art-template-loader引入外部子模板问题

### ISSUE THREAD

**Issue by sjoooo123** [aui/art-template#401]
### 1\. 错误描述
1、header.art代码如下：
![image](https://cloud.githubusercontent.com/assets/22810581/26137784/f3d6cd48-3af6-11e7-8870-ed8a1f0561c9.png)
引用header.art文件的body.art文件如下：
![image](https://cloud.githubusercontent.com/assets/22810581/26137792/1861645c-3af7-11e7-893d-7e458eb3701b.png)
body.art中：
<%  include('./component/header.art', {
      title: title
    }) 
%>
title值没有绘制成功；
2、body.art文件中的这段代码如何采用模板语法绘制
{{each responsedata value i}}
       <li><a class="n3ellipsis" href="{{value.url}}" target="_blank">{{value.name}}</a></li> 
{{/each}}
，如何在js文件中使用？
目前调用的index.js如下：
![image](https://cloud.githubusercontent.com/assets/22810581/26137865/b5ed7c7e-3af7-11e7-8bab-b6297603a2c0.png)
请问在最下面的draw函数中，如何使用body.art这个文件进行数据绘制？
### 2\. 版本号
"art-template": "^4.9.1", 
"art-template-loader": "^1.4.2",
### 3\. NodeJS 或浏览器类型与版本
nodejs -v6.2.0
google chrome 版本 58.0.3029.96 (64-bit)
### 4\. 可重现的 Demo
Demo暂时无法重现，详情请看错误描述，谢谢

**Comment by sjoooo123** [comment]
第二个问题知道怎么弄了，第一个问题还不知道

**Comment by aui** [comment]
你提的问题我看了三遍，依然没看懂

**Comment by sjoooo123** [comment]
就是在art模板文件里面，引入子模板，像这样
<% include('./header.art', {
      title: title
}) %>，
传入title参数的值，但是没有成功渲染，问题这样描述能清楚吗？

**Comment by sjoooo123** [comment]
另外就是在webpack里面，是如何打包的呢，我打包生成的文件里面，打开页面，无法渲染

**Comment by aui** [comment]
你应该提供一个 demo，并且去掉任何无关的代码

**Comment by sjoooo123** [comment]
好的，我整理下，到时候发出来

**Comment by sjoooo123** [comment]
webpack构建的项目发布出来也看不到源代码，该怎么提供呢？

**Comment by sjoooo123** [comment]
可以提供一个可以正常运行和打包的DEMO，供大家下载吗？

**Comment by aui** [comment]
1. 没有理解我说的 DEMO 是什么吗？它是可以让我可以运行并重现的案例，这样我才能使用它哪里出了问题，而不是靠现在这样猜测
2. 为什么你从来不去看项目中的 example 目录？

鉴于你提问之前没有准备好，所以关闭问题。为了保持高效的沟通、解决问题，以后类似这样的问题都将直接关闭。
