### ISSUE TITLE
请问如何对artTemplate 作node端的全局设置

### ISSUE THREAD

**Issue by Levi0701** [aui/art-template#410]
看文档中对artTemplate的配置都是对template.default作配置，但是如果是在node端的话，这个template对象如何获取呢？我试了用require('art-template')获取到的对象，只是那三个构造方法，但是没有配置对象。如何将template的配置对象作为中间件插入到express的全局作用域中呢？谢谢~~

**Comment by aui** [comment]
require('art-template').defaults

**Comment by Levi0701** [comment]
我在app.js里使用了

let artTemplate = require('art-template').defaults;
console.log('arttemplate: ', artTemplate);

但是控制台输出的是:
arttemplate:  { '$extend': [Function] }

不是真正的defaults对象

**Comment by aui** [comment]
它继承自 defaults，也是你要的对象

**Comment by Levi0701** [comment]
哦，好的。谢谢，另外，如何将它作用到express的全局作用域？让每一个模板都生效呢？直接配置完就可以？还是需要app.use(template)?

**Comment by aui** [comment]
直接对它写入配置即可全局生效

**Comment by Levi0701** [comment]
好的，非常感谢~~期待artTemplate的功能越来越强大，越做越好~~~
