### ISSUE TITLE
4.10.0编译产出异常

### ISSUE THREAD

**Issue by win7killer** [aui/art-template#412]
从4.8.2（4.9.1正常） 更新至4.10.0，编译产出异常，编译中无报错

### 1\. 当模板中出现  `src=“xxx”` 的时候，编译产出会变成  ` [object Object]`， img的src和script的src都会【有配合html-webpack-plugin使用需求，所以会有script的src】
产出示例： 
```
<img [object Object] alt="" class="logo">
<script [object Object] charset="utf-8"></script>
```

**Comment by aui** [comment]
art-template-loader@1.4.3 已经修复此问题

**Comment by win7killer** [comment]
"art-template-loader@1.4.3 已经修复此问题 "

棒棒的
