### ISSUE TITLE
关于web-ie使用include的问题

### ISSUE THREAD

**Issue by lwlapp** [aui/art-template#415]
web-ie 使用时。。如何把所有模板压缩到一个js中一次加载。。这样就不要每次使用时页面中重复定义<script id="test" type="text/html">像这样定义    然后我才能include ,                  要达的目的是：在任何页面使用时只须引入模板资源集js文件  ，页面个性化直接include 引用就可。。。

**Comment by aui** [comment]
请移步到文档 API 部分

**Comment by lwlapp** [comment]
OK,谢谢
