### ISSUE TITLE
ie11下出现SCRIPT1014: 无效字符的问题

### ISSUE THREAD

**Issue by Gegex** [aui/art-template#417]
### 1\. 错误描述
我模板代码单独写到一个js文件中：
var tpl_face = template.compile(`{{each data as url key}}<li title="{{key}}"><img src="{{ faceUrl + url}}"></li>{{/each}}`);
然后使用`('#facetitle').html(tpl_face({ data: faceMap, faceUrl: faceUrl }));`
ie11下出现SCRIPT1014: 无效字符，chrome和firefox下正常
无效字符为`符号,template.compile(``);
### 2\. 版本号
version="3.0.0"
### 3\. NodeJS `或浏览器类型与版本`
浏览器版本

**Comment by aui** [comment]
1. 你没有给出有助于他人调试的 demo
2. v3.0.0 版本已经不再更新

**Comment by Gegex** [comment]
demo:http://www.works8.com/demo/1.html

使用最新版的也出现同样的问题

**Comment by aui** [comment]
> 既然浏览器有报错信息，你可以根据这些信息排查自己代码问题，例如使用了 IE 不支持的 JS 语法（ES6）

**Comment by Gegex** [comment]
就是因为没检查出来问题呀，js就几行：
1，引入jquery
2，引入template.js
3，`template.config('escape', false);
var tpl_face = template.compile(`{{each data as url key}}<li title="{{key}}"><img src="{{ faceUrl + url}}"></li>{{/each}}`);`,
4，    
<script type="text/javascript">
    var faceUrl = "./face/";
    var faceMap = {
        "[可爱]": "emoji_01.png",
        "[大笑]": "emoji_00.png"
    };

    $('#facetitle').html(tpl_face({
        data: faceMap,
        faceUrl: faceUrl
    }));
    </script>

**Comment by aui** [comment]
> 无效字符为`符号

这是你开头说的错误信息，IE 不支持。

**Comment by aui** [comment]
如果你自己用 IE 11 的调试器也可以轻易的找到问题原因

**Comment by Gegex** [comment]
![image](https://user-images.githubusercontent.com/12454593/27161535-7e017b30-51ae-11e7-8f8a-4f1f3e9b6dad.png) 
新手，见笑了。
