### ISSUE TITLE
能wiki说明一下项目搭建、运行环境、打包环境吗？

### ISSUE THREAD

**Issue by GongLe** [aui/art-template#419]
能wiki说明一下项目搭建、运行环境、打包环境吗？作为不是专业搞前端开发的，最近两年前端发展太猛，项目结构已经看不懂了，敬爱的作者能布道一下吗？

**Comment by aui** [comment]
可以依次搜索相关知识：

1. 运行环境：nodejs
2. 包管理、构建命令管理：npm
3. 编译器（打包）：webpack
4. 语言：es6
5. 测试框架：mocha

**Comment by GongLe** [comment]
谢谢！
