### ISSUE TITLE
通过 art-template-loader 加载进来的模板，不能使用过滤器

### ISSUE THREAD

**Issue by dubhe** [aui/art-template#420]
webpack + art-template-loader 加载模板

---------
part.art
`{{value | detailurl}}`
---------
main.js

```
import template from './template'
import render from 'part.art'

template.defaults.imports.detailurl = function(){}
```

---------
chrome:
`detailurl is not a function`

如果 我不使用 require，直接用 template.compile，就不会有这个问题
我想问下，这种情况是要如何添加过滤器呢 ？
我看到art template loader npm 上有这种 demo
var runtime = require('art-template/lib/runtime');
runtime.dateFormat = function(){ /*[...]*/ };
var html = require('./index.art');

但是我没有找到 web 的，不知道要怎么做呢 ？

**Comment by aui** [comment]
1. 请给出直接可以运行的 demo
2. 总结你的问题

**Comment by dubhe** [comment]
[art-demo.zip](https://github.com/aui/art-template/files/1074373/art-demo.zip)
你看看，
node 里面，设置 template.defaults.imports 有效
在 web 里面，设置了 template.defaults.imports，如果使用 template. compile,可以使用这些过滤器，
如果 是用 art-template-loader，require 进来的 render，无法使用这些过滤器

**Comment by aui** [comment]
<https://aui.github.io/art-template/webpack/#Filter>

**Comment by 758915145** [comment]
> 你可能没有弄明白 webpack loader 的用途，template 和 less、sass 的 loader 都是直接输出编译后的代码，编译后的代码不依赖引擎本身，因此在业务中载入 art-template 其实没有任何作用。
> 
> art-template-loader 关于扩展 filter 和 art-template 不一样，文档有特别说明：
> 
> https://aui.github.io/art-template/webpack/#Filter

webpack的这个文档里载入了 art-template/lib/runtime，是不是与你说的：**因此在业务中载入 art-template 其实没有任何作用** 冲突了呢，我使用 art-template-loader 之后也不知道怎么使用filter了呢：
```
var runtime = require('art-template/lib/runtime');
runtime.dateFormat = function(date, format){ /*[...]*/ };
var html = require('./index.art');
```

**Comment by aui** [comment]
完整的 art-template 包含了编译功能与过滤器需要的 runtime。webpack 是预编译，所以业务代码不需要引入完整的 art-template，有且只有在需要拓展过滤器的时需要引入 runtime

**Comment by 758915145** [comment]
> 完整的 art-template 包含了编译功能与过滤器需要的 runtime。webpack 是预编译，所以业务代码不需要引入完整的 art-template，有且只有在需要拓展过滤器的时需要引入 runtime

谢谢，我发现以下代码无效的原因是使用了 html-webpack-plugin 插件来读取了里面的 html，导致那个 html 里不能正常使用 filter 了，解决方法是不使用 html-webpack-plugin 来加载含有 art-template 模板的 html 文件
```
var runtime = require('art-template/lib/runtime');
runtime.dateFormat = function(date, format){ /*[...]*/ };
var html = require('./index.html');
```
