### ISSUE TITLE
Java thymeleaf 模板报错，单元测试无法通过

### ISSUE THREAD

**Issue by chang0022** [aui/art-template#421]
错误描述：
`<input type="checkbox" {{showInTodayBoutique ? 'checked' : ''}} id="showInTodayBoutique" value="showInTodayBoutique">`
三元运算符在 input 单标签属性标签会报错，如下图：
![image](https://user-images.githubusercontent.com/6067222/27129316-5d1b2404-5134-11e7-8f83-95c1d8501cd6.png)

![image](https://user-images.githubusercontent.com/6067222/27130087-4586c250-5137-11e7-8c08-8c68c80db6d4.png)

然后测试无法通过，错误如下：

![qq 20170614193403](https://user-images.githubusercontent.com/6067222/27130264-31e6cdca-5138-11e7-939b-b0bc8520260c.png)

该 IDE 错误在前端状态下是可以通过，但 Java 模板渲染中无法通过单元测试。

解决方法使用 if else
``` 
{{if showInTodayBoutique}}
    <input type="checkbox" checked id="showInTodayBoutique" value="showInTodayBoutique">今日精品
 {{else}}
    <input type="checkbox" id="showInTodayBoutique" value="showInTodayBoutique">今日精品
{{/if}}
```

谢谢。可能不算BUG。但是否有解决方法？

**Comment by aui** [comment]
“如果一个 BUG 无法被他人重现，这个 BUG 也无法被他人解决”

你应该：

1. 提供直接可以运行的 DEMO
2. 删除无关代码（Java）

**Comment by chang0022** [comment]
现在问题是DEMO是OK的，但IDE (Webstorm)会有错误提示。然后通过JAVA渲染页面，错误无法通过。
简单来说 就是 三目运算符 无法在 单属性标签上面使用。
![image](https://user-images.githubusercontent.com/6067222/27131245-693aa1da-513c-11e7-87f0-2f2323c2d450.png)

**Comment by aui** [comment]
> template.compile('<input type="checkbox" {{showInTodayBoutique ? "checked" : ""}} id="showInTodayBoutique" value="showInTodayBoutique">')({showInTodayBoutique: true})
> // "<input type="checkbox" checked id="showInTodayBoutique" value="showInTodayBoutique">"

art-template 是字符串模板，它只负责按照模板逻辑输出字符串，至于 java 单元测试、IDE、浏览器 html 是否合法，都不是他的职责——所以这些问题都需要你自己去排查，而不是将一堆不清晰的问题交给其他人。
