### ISSUE TITLE
php 数据渲染和这个模板渲染工具里面的if有冲突

### ISSUE THREAD

**Issue by web-oop** [aui/art-template#423]
<script id="test" type="text/html">
{{each Data as item}}
    {{if item.type=="1"}}
    找人
    {{else if item.type=="2"}}
    找财产
    {{else}}
    其他
    {{/if}}
{{/each}}
</script>

<script>

var data ={Data:[{type:"1"},{type:"2"},{type:"3"}]};
var html = template('test', data);
document.getElementById('content').innerHTML = html;
</script>

<div id="content">
    
    {}
    其他
    {}
    
    {}
    其他
    {}
    
    {}
    其他
    {}
    
</div>

**Comment by aui** [comment]
这种是业务需要想办法去规避的。

1. 修改 php 的模板引擎界定符或 art-template 界定符
2. 避免 php 模板引擎解析 art-template 模板

**Comment by web-oop** [comment]
php后端模板引擎界定符我不懂怎么改，art-template 界定符怎么去修改知道吗？

**Comment by aui** [comment]
你需要我把文档给你找出来吗？我又不是客服

**Comment by latel** [comment]
顶，文档都不会去查吗
