### ISSUE TITLE
不能解析两次吗

### ISSUE THREAD

**Issue by uezhui** [aui/art-template#427]
function abc() {
			$('.city').html(template('city', citys))
		}
abc() // 这样没问题
但我改变citys的值后再次调用abc()
就出现了
"TemplateError template not found: Cannot read property 'value' of null"
也就是说template方法只能调用一次，多次调用会出现模板错误情况
求解...

**Comment by aui** [comment]
对于你提问的内容，我不太理解：你新建 Issues 的时候是没有出现下面提问规则吗？

```
<!--
提交 Issues 需要遵循如下规则：

一、BUG：
1. 使用简单扼要的标题与内容
2. 删除无关代码、提供可以直接运行的 DEMO
3. art-template 版本、环境版本（NodeJS 或浏览器）

二、其他问题：
1. 不建议提交使用问题，除非文档没有写清楚
2. 提问之前请在文档站点、CHANGELOG.md、已有的 Issues 寻找答案

很遗憾的是大部分开发者都不会提问，希望上述大段文字没有打扰到你
-->
```

还是说你不是程序员没有 Debug 能力？不会提 BUG？还是说习惯了要别人给你现成的答案？

**Comment by uezhui** [comment]
我没觉得我提的问题有什么问题啊，你写个模板，看下abc能不能调用两次，调用两次会不会报错!!!

**Comment by aui** [comment]
先不说你自己没有没有排查。你按照要求提交了 BUG 了没？

**Comment by aui** [comment]
> "我没觉得我提的问题有什么问题啊"

随便看了下你在其他项目提的问题，这样的问题你让别人如何解决？

![a](https://user-images.githubusercontent.com/1791748/27320400-aae87ba8-55c8-11e7-9ffe-dba0a36c73bf.png)

你要尽可能的一次性描述清楚，这样才能高效的与别人合作解决问题。

**Comment by uezhui** [comment]
我是在相应的项目提的问题有什么问题，又不是全局搜索，我只是叙述我遇到的问题，我也不知道是不是你代码的问题还是问题，你文档写的这么简洁，全部都得靠自己摸索
