### ISSUE TITLE
3.0与4.0有什么区别，直接替换下库文件art-template.js就OK了吗？

### ISSUE THREAD

**Issue by pannysp** [aui/art-template#432]
项目里部署3.0好久了，那么3.0与4.0有什么区别，有必要升级吗？
直接替换下库文件art-template.js就OK了吗？
4.0的话tmod tpl不支持了，那编译的命令改什么了？

**Comment by aui** [comment]
千万不要升级！文档地址有变更，我担心你找不到或者看不懂，所以不推荐你升级。
