### ISSUE TITLE
模板中含有 name="nodeName"这样的代码时，Uncaught TypeError: a.nodeName.toLowerCase is not a function

### ISSUE THREAD

**Issue by XieleiFighting** [aui/art-template#435]
### 版本：4.10.1

代码：

    <script type="text/html" id="manageTpl">

    <input type="hidden" name="parentId" value="{{parentId}}">

    <input name="nodeName" type="text" placeholder="模块名称" class="form-control">

    </script>

js:

    var html = template('manageTpl', {parentId: "0"});

异常：

    Uncaught TypeError: a.nodeName.toLowerCase is not a function`

**Comment by aui** [comment]
请提供可以 **直接** 运行的 demo

**Comment by aui** [comment]
@XieleiFighting 从你抛错消息 “a.nodeName.toLowerCase is not a function” 来说，这不属于目版引擎的抛出错误。我之所以让你提供直接可运行的 demo，你可以通过建立 demo 的过程发现问题。
