### ISSUE TITLE
对于undefined或null的变量使用原文输出语法{{@value}}为什么不跟3.x版本一样不输出

### ISSUE THREAD

**Issue by chenhongtu** [aui/art-template#436]
对于undefined或null的变量使用原文输出语法{{@value}}现在会直接输出undefined或null字符串，为什么不跟3.x一样不输出呢，这样感觉很不方便

**Comment by aui** [comment]
为了性能上的优化，所以这里有改变。

可以：

1. 使用标准语法
2. 如果类型不会为 `number`，可以这样 `<%-value || ''%>` 解决
