### ISSUE TITLE
art-template可以解析JSON数据结构里带的部分字符串形式的结构吗

### ISSUE THREAD

**Issue by minminvan** [aui/art-template#438]
hgContent: {
likeCnt: 0,
commentCnt: 0,
viewCnt: 63,
thumbImageUrl: "http://10.19.95.100/uimg/MFS/show/149025461852290474.jpg",
smallImageUrl: "http://10.19.95.100/uimg/MFS/show/149025461852290474_340x340.jpg",
jumpTo: "",
publishTime: "2017-03-23 15:36:59",
displayJson: "[{"smallImageUrl":"http://10.19.95.100/uimg/MFS/show/149025461871097646_340x340.jpg","productCode":"000000000120875068","componType":"4","venderCode":"0000000000"},{"smallImageUrl":"http://10.19.95.100/uimg/MFS/show/149025461892068396_340x340.jpg","productCode":"000000000120875069","componType":"4","venderCode":"0000000000"},{"smallImageUrl":"http://10.19.95.100/uimg/MFS/show/149025461911161778_340x340.jpg","productCode":"000000000120877161","componType":"4","venderCode":"0000000000"},{"smallImageUrl":"http://10.19.95.100/uimg/MFS/show/149025461925994123_340x340.jpg","productCode":"000000000120875649","componType":"4","venderCode":"0000000000"}]"
}
```
主数据是JSON格式，但是里面又包含了displayJson子结构是字符串形式的，这样的字符串形式可以用art-template来处理吗

**Comment by aui** [comment]
`<% var json =  $imports.JSON.parse(string) %>`
