### ISSUE TITLE
大神，我能不能问一个可能不太相关的问题。因为我实在找不到答案。。

### ISSUE THREAD

**Issue by wuxinzhe** [aui/art-template#443]
问题其实也很简单，就是我想用webpack下打包一些常用的UI组件，然后有一个项目，是用seajs来做模块加载和管理的，为什么我打包出来的js文件不能像你的template-web那样，可以直接在requireJs或seajs这样的工具下引用？我的执行以后会报错，错误提示是我引用的对象是null或非对象。

**Comment by aui** [comment]
请不要提使用问题。另外，我不是神仙，不能猜测你的问题出在哪里了——你根本没有提供任何有价值的问题描述信息。
