### ISSUE TITLE
ie8 中Object.defineProperty会报错？我用的是最新版的

### ISSUE THREAD

**Issue by cuihua111** [aui/art-template#447]

**Comment by aui** [comment]
希望能够提供 demo，因为测试代码是正常运行的，否则这个问题就一只会延续下去了

**Comment by aui** [comment]
```
一、提交 Bug
1. 标题：简单扼要，便于快速检索
2. 重现 DEMO：删除无关代码、提供可以 **直接** 可运行的 Demo（不是代码片段）
3. 重现环境：art-template 版本、环境版本（NodeJS 或浏览器
```

**Comment by cuihua111** [comment]
https://github.com/cuihua111/arttemplateBug.git demo地址

**Comment by aui** [comment]
<https://aui.github.io/art-template/docs/installation.html#浏览器>

**Comment by cuihua111** [comment]
down下来直接在页面引用es5-shim.js中会报相同的错误。还是这个属性

**Comment by aui** [comment]
那你为啥不提供完整的 demo 呢？

**Comment by cuihua111** [comment]
我是刚看你发的链接里面有个shimjs，我之前是没有用这个的。但是现在有这个之后还是一样会报错啊

**Comment by aui** [comment]
请补充 demo。

**Comment by cuihua111** [comment]
可以了

**Comment by cuihua111** [comment]
已经补充了。

**Comment by aui** [comment]
你还需要引用其他文件。文档提供的示例 404 了，已经修正，可以根据示例来解决。

**Comment by cuihua111** [comment]
好的，感谢

**Comment by cuihua111** [comment]
补充2.0 。按照示例引了另外两个文件，但是还是会报bind方法错误

**Comment by aui** [comment]
你能不能按照我要求提供一次完整的 demo？这样好歹可以让人在虚拟机中调试。不然我们为什么要浪费时间来回低效的沟通、猜测问题？

**Comment by cuihua111** [comment]
可以了。谢谢耐心指导。

**Comment by aui** [comment]
我没啥耐心，要不是看在 IE8 可能会有兼容问题，才网开一面。如果按照我设置的提问规范，想你这样不负责的问题，通常直接就关闭了。

**Comment by cuihua111** [comment]
我是因为比较菜，很多东西不懂，不是说想省事不按照规范- -，不管咋说吧，谢谢你了
