### ISSUE TITLE
可以多重继承吗？

### ISSUE THREAD

**Issue by lucaszong** [aui/art-template#448]
html1:  {{block 'content'}}{{/block}}

html2: {block 'content'}}   {block 'inner'}}{{/block}}   {{/block}}

html3: {block 'inner'}}Demo{{/block}}

 为什么html3中 的字符Demo无法显示

**Comment by aui** [comment]
问题关闭原因：
```
1. 请附带可以 **直接** 重现的 Demo，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
```

**Comment by BanKnight** [comment]
我测试出来也是相同的结果
