### ISSUE TITLE
为什么在style标签里面的html代码不能使用juqery了。请问怎么解决。

### ISSUE THREAD

**Issue by city8866** [aui/art-template#453]
你好，虽然这个问题让你很不高兴。但是我个人一直没有搞明白。还希望您指点一二。
1.我引入template_web.js后，然后使用按照例子那样做，但是有个问题，比如：
`<div id="content1"></div>
            <script id="test1" type="text/html">
            <a href="#" class="send">发送</a>
             </script>
`
然后js里是这样
`
$(document).ready(function(){
    $(".send").on('click',function(){
         console.log('print');
     });
})
`
就是我这个点击事件不能使用。也就是jquery不生效。请问下，这个是引入art-template后出现冲突的问题吗？希望能给解答一下，好多代码都是类似上面的，已经赞助过了。项目比较急，感谢。已经赞助过了。

**Comment by aui** [comment]
1. 我已经明确在 issue 规则中写了不接受使用咨询
2. 你的问题和 art-template 无关
3. 你项目急不急和我没关系
4. 赞助了不代表我要破例给你提供技术支持，况且你根本没有赞助
