### ISSUE TITLE
express中res.render()函数，当渲染数据中出现多层数组嵌套时就会栈溢出是什么情况？

### ISSUE THREAD

**Issue by sunhuayu** [aui/art-template#457]
我渲染的数据中有两层数组嵌套，我记得老版本是没有问题的，为什么新版本会报错？具体错误信息如下：

RangeError: Maximum call stack size exceeded
    at toType (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:6:47)
    at extend (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:17:16)
    at extend (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:28:33)
    at extend (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:28:33)
    at extend (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:28:33)
    at extend (C:\Users\sunhuayu\Desktop\H5正
课课程\第24天\1,增删改查接口\node_modules\art-
template\lib\compile\adapter\extend.js:28:33)

**Comment by aui** [comment]
少年，学习技术第一步就是要学会如何正确的提问，你新建 issues 的时候显示了提问应该遵循的规则，它就是为你们这些牛逼的新人准备的。

**Comment by sunhuayu** [comment]
art-template在处理渲染数据时，是不是进行的浅拷贝(甚至没有拷贝)？而且尝试对渲染数据进行加工了？
我使用的是mongoDB数据库，用的mongoose进行连接。使用Schema查询出的数据对象，其属性是有类型限制的，如果某个属性是数组，你不能把它修改为其他类型，修改之后它还会是数组。是不是art-template在进行渲染数据加工时，使用递归对数组进行加工，然是不能把数组改为其他类型，结果导致的递归死循环？

我已经尝试把数据进行一次深拷贝，然后再渲染，这个问题就没有了。

**Comment by aui** [comment]
你应该去掉无关环境提炼一个重现的 DEMO，自己先定位问题后再提出问题——而不是让别人帮你猜测 BUG（我们又不是神仙）。
