### ISSUE TITLE
如何去除模版的标准语法{{}}

### ISSUE THREAD

**Issue by ymzuiku** [aui/art-template#458]
vue中的{{}}获取变量和标准模版语法冲突，请问如何把art-template的标准模版语法去掉？
用了vue的代码:
```
  <div id="app">
    vue:{{ message }}
  </div>

var app1 = new Vue({
      el: '#app',
      data: {
        message: '页面加载于 ' + new Date()
      }
   })
```

**Comment by aui** [comment]
不再提供使用问题咨询。

**Comment by chenyuan122912** [comment]
用原生语法 <%%>


chenyuan122912@sina.com
 
发件人： ym
发送时间： 2017-08-08 18:57
收件人： aui/art-template
抄送： Subscribed
主题： [aui/art-template] 如何去除模版的标准语法{{}} (#458)
vue中的{{}}获取变量和标准模版语法冲突，请问如何把art-template的标准模版语法去掉？
用了vue的代码:
  <div id="app">
    vue:{{ message }}
  </div>
var app1 = new Vue({
      el: '#app',
      data: {
        message: '页面加载于 ' + new Date()
      }
   })
