### ISSUE TITLE
为什么jsp页面中使用 {{each results as data i}}  循环不识别呢？？

### ISSUE THREAD

**Issue by FeiCheung** [aui/art-template#465]
{{each results as data i}}
			<tr>
				<td>data.lineid</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
				<td>1</td>
			</tr>
			{{/each}}

我在jsp 中使用  这段循环体 跟本没有循环 是哪儿里的问题？ 之前手机app项目中一切正常  急急急

**Comment by aui** [comment]
先学会提问再来提问
