### ISSUE TITLE
在循环过程中同一个变量赋值后，下次循环使用上次的值问题

### ISSUE THREAD

**Issue by cfanbo** [aui/art-template#466]
{{set temp = data.sub.content}}

这个语法是每次都生成一个新变量，但有时候，需要将本次的值保存到一个变量中，以备下次使用，试了将set 命令删除，会打印出来，目前 在前面使用  来实现了，不知有无更好的方法

**Comment by aui** [comment]
问题关闭原因：

问题关闭原因：

```
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
```
