### ISSUE TITLE
是否支持block嵌套

### ISSUE THREAD

**Issue by tangye1234** [aui/art-template#468]
[参考Pug的案例](https://gist.github.com/joepie91/c0069ab0e0da40cc7b54b8c2203befe1#template-inheritance-in-pug)

### Things of note:

* Overriding a block is optional. If you don't override a block, it will simply contain either the default content from the base template (if any is specified), or no content at all (if not).
You can have an unlimited number of blocks with different names - for example, the one in our example is called content. You can decide to override any of them from a template, all of them, or none at all. It's up to you.
* You can nest multiple blocks with different names. This can be useful for more complex layout variations.
* You can have multiple levels of inheritance - any template you are inheriting from can itself inherit from another template. This can be especially useful in combination with nested blocks, for complex cases.

话说支持extend多级，同时要支持block嵌套是一个基本的模板渲染功能。

**Comment by tangye1234** [comment]
如题，很多nodejs端，老牌的模板渲染器都支持 nested block，在稍微复杂的一点的场景下，为了复用，而不得不采用这种方式。

**Comment by tangye1234** [comment]
#487 fixes this problem.

**Comment by aui** [comment]
已经发布

**Comment by zhaiyuzhai** [comment]
好像还是不能嵌套：
layout.art:

{{block  ‘block1’}}
  <header class="search">
    {{block 'header1'}}
    {{/block}}
    {{block 'header2'}}
    {{/block}}
    {{block 'header3'}}
    {{/block}}
    {{block 'header4'}}
    {{/block}}
    {{block 'header5'}}
    {{/block}}
  </header>
{{/block}}

content.art:

{{block 'header1'}}
<div class="search_item grow">
  <input class="input border" type="text" placeholder="请输入搜索关键字">
</div>
{{/block}}
这么写好像不管用
