### ISSUE TITLE
English Translation, please!

### ISSUE THREAD

**Issue by Javiani** [aui/art-template#474]
Hi!

First of all, thanks for this great library. Unfortunately all documentations and information about it is in a language that for many people is totally impossible to understand...

Do you plan to translate it to English some day? That's what is avoiding my company to adopt this great library.

Thank you!

**Comment by aui** [comment]
I plan to translate the document into english, but it will take some time. Thank you for your attention.

**Comment by yangkean** [comment]
@aui ，if you want help, I am glad to help you to translate the document into english.

**Comment by aui** [comment]
@yangkean 好，非常感谢！我先整理好目前的文档，然后通知你

**Comment by yangkean** [comment]
@aui ，好滴：）

**Comment by aui** [comment]
@yangkean 

## 英文翻译步骤

一、克隆 art-template-docs 仓库，然后 npm install && npm start

二、先将以下文件复制到 source/zh-cn 目录

1. source/docs/
2. source/express/
3. source/koa/
4. source/webpack/
5. source/index.md

三、依次将上述目录或文件翻译成英文，然后站点就默认为英文文档了

**Comment by aui** [comment]
@Javiani English site: <https://aui.github.io/art-template/>

**Comment by Javiani** [comment]
WOW, so quick! Very nice!!

Thank you very much guys, I´m sure that It will help not only me but many others devs out there!
I´ll share it with the team and use it, finally!

Good job! 👍
