### ISSUE TITLE
您好 想问下模板复用的问题

### ISSUE THREAD

**Issue by peiluojia** [aui/art-template#481]
```
Uncaught Error: test:5:5
    3|     <h2 class="title">{{title}}</h2>
    4| 
 >> 5|     {{include './template/template.art'}}
    6| 
    7| 

RuntimeError: template not found: Cannot read property 'value' of null
```
我想引用template文件夹下的子模版 会报错 这是什么问题呢 子模版必须在同一页面吗 模板的格式必须是art吗

还有就是想写一个模板然后其它页面都复用这么模板该用什么属性呢 我是菜鸟 谢谢啦

**Comment by aui** [comment]
问题关闭原因：

1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题

**Comment by imxood** [comment]
`
var html = template("/tpl/face_dialog.art", {
        user: {
            name: 'aui'
        }
});
`
遇到同样的问题，最后编译源码生成未压缩的template-web.js，调试发现，原来是只有使用node才支持文件，不使用node，这里的template()的第一个参数是ElementId,,,,,
`
if (detectNode) {
var fs = __webpack_require__(5);
                return fs.readFileSync(filename, 'utf8');
            } else {
                var elem = document.getElementById(filename);
                return elem.value || elem.innerHTML;
            }
`
