### ISSUE TITLE
如何在模板中输出 JSON 内容，而不被转义

### ISSUE THREAD

**Issue by wangjunji** [aui/art-template#482]
```
var user = {
    name: 'Tom',
    age: 21
}
```
假设后端有这样一个变量，希望动态输出到前端模板的script中去
```
<script>
{{if user}}
var user = '{{user.name}}'; //如果是字符串没问题
{{/if}}
</scirpt>
```
但如果直接传对象，渲染就有问题
```
<script>
{{if user}}
var user = {{user}}; 
{{/if}}
</scirpt>
```
这样写渲染得到的结果是：
```
var user = { & #34;name&# 34;: & #34;Tom&# 34;,& #34;age&# 34;: 21};
```
显然是经过html转义过了，如果用`{{@user}}`，原样输出，得到的结果是：
```
var user = [Object object];
```
请问该如何实现直接在script中输出对象呢？

**Comment by aui** [comment]
可以使用 `{{@user | JSON.stringify}}` 来输出 object 内容

**Comment by wangjunji** [comment]
我后来用了{{@$imports.JSON.stringify(user)}}也能实现，不过你的方法更加直观。还有一个问题就是，如果这个object里带function怎么办？stringify会忽略function @aui

比如：
```
var option = {
    option1:'',
    option2:'',
    success: function(){
    },
    fail:function(){
    }
}
```

**Comment by aui** [comment]
issues 规则我有明确说明不提供 art-template 的使用帮助。你可以自己处理成字符串然后原文输出。

**Comment by ManfredHu** [comment]
`{{@user | JSON.stringify}}`对应的原始语法会变成什么？
