### ISSUE TITLE
关于lib\compile\adapter\extend.js

### ISSUE THREAD

**Issue by ugrg** [aui/art-template#483]
刚新建的一个express工程,加载了`express-art-template`,由于还没有设置任何routes,所在我在直接访问时肯定会报错,走进404的状态当中.
但这时,代码就会报
```
TypeError: target.hasOwnProperty is not a function
```

debug跟下来,发现是在递归遍历对象时,出现了一个对像的__proto__ = null的情况,这个对像应该是一个Error对像,不清楚为什么他的__proto__为什么会是null.

推荐你们把这里的`target.hasOwnProperty`修改成`Object.hasOwnProperty.call(target, index)`,以避免这一错误的发生.

**Comment by aui** [comment]
可以帮忙提交一个 pr 吗？

**Comment by aui** [comment]
已经修复问题，非常感谢！

**Comment by mingjiu** [comment]
@aui https://github.com/aui/art-template/issues/459 这个issue 应该也要关闭掉了吧
