### ISSUE TITLE
浏览器版本怎么自定义函数

### ISSUE THREAD

**Issue by ruanzy** [aui/art-template#492]
浏览器版本自定义函数
`			template.defaults.imports.aa = function (v, arr) {
				return arr.indexOf(v) > -1;
			};`

页面代码报错：
{{aa(value, ['a']))}}

**Comment by aui** [comment]
```
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
```
