### ISSUE TITLE
文本数据中包含标签无法被渲染

### ISSUE THREAD

**Issue by shmchen** [aui/art-template#494]
比如模板传入数据data，data.name = “<‘font’ style='color:red'>屌炸天</‘font’>--”(为防止被GitHub这边解析，font标签加个‘号)
模板输出内容显示到网页还是完整的字符串，标签未能被浏览器识别；
这种情况是否有哪个地方可以设置？渲染得到的HTML不管是innerHtml，还是innerText，其中包含的标签都无法被渲染

**Comment by aui** [comment]
```
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
```

使用之前，请阅读文档；提问之前，请阅读提问规范。
