### ISSUE TITLE
在iframe中使用出现的混乱情况

### ISSUE THREAD

**Issue by evildancer** [aui/art-template#500]
我的页面中有一个iframe的容器，在当前页和iframe中都同时使用到了template，但是意外出现了。当iframe中的template被使用后，它的父级页面中的template的使用出错了。
这是使用旧版本报的错（具体是哪个版本忘掉了）：
![image](https://user-images.githubusercontent.com/13979614/34189987-3dddd65c-e579-11e7-80e4-ff0039e935e8.png)

调试后，发现是document被改变了。iframe中template被使用后，不管是父级页面还是iframe中的template使用都会从iframe下的document查找元素。导致父级页面元素根本找不到。

这是使用最新新版本报的错：
![image](https://user-images.githubusercontent.com/13979614/34189913-d8e874be-e578-11e7-8531-14a6e939c10b.png)

**Comment by aui** [comment]
不合格的问题直接关闭。

如果你想让别人给你解决问题，就应该考虑写一个有诚意的问题，而不是只贴一段无法被他人重现莫名的错误。

**Comment by evildancer** [comment]
我不是想让别人解决的问题，我只是反馈一下该插件的问题。如果作者大大您不愿意了解关闭就好了。感谢您的回复
