### ISSUE TITLE
art-template支持require.js加载吗？如果支持如何配置？

### ISSUE THREAD

**Issue by cnyet** [aui/art-template#505]
我试着用require.js加载art-template，但是都不成功。不知道是不是我配置有误：
require.config({
    paths:{
      "template": "lib/art-template"
    },
    shim: {
      "template": {
        exports: "template"
      }
    }
});

**Comment by Nigular** [comment]
我用过可以，应该是你后面的调用方式问题。另外，art-template不需要依赖jquery吧。可以参考下面代码：
require.config({
  paths: {
    jquery: "./lib/jquery-1.10.2.min",
    template:"./lib/template-web"
  }
});
define(["jquery","template"], function($,template) {
   var htmlstr= template('box_tmp', {article:article});
   $("#box").html(htmlstr);
}）

**Comment by cnyet** [comment]
非常感谢，是我调用的问题，已解决。

**Comment by cnyet** [comment]
@Nigular 非常感谢，是我调用的问题，已解决。
