### ISSUE TITLE
是否能提供类似vue的数据绑定功能?

### ISSUE THREAD

**Issue by Jiangshan00001** [aui/art-template#512]
喜欢art-template的简单模版规则, 又需要vue的数据绑定的自动渲染功能.
问下,是否可以有某种方式实现两者的结合?
例如:
v= ArtVue('输出:html中的元素id', '输入:模版的id',  {渲染使用的数据 });
后期数据变化,可以引起自动渲染?

**Comment by aui** [comment]
这个方向和 art-template 差的挺远的，需要完全重写。我猜应该有很多类似的库 :-)

**Comment by kunl** [comment]
直接用 vue 岂不是更方便
