### ISSUE TITLE
发现经不起反复压测

### ISSUE THREAD

**Issue by DENNIE-HONG** [aui/art-template#519]
node做后端，--prof 发现art-template消耗cpu
反复压测多次，QPS渐渐下降，最后降到30，而且长时间不能恢复QPS!!!
即使页面什么data都没有，也会QPS显著下降问题！！！！
最后改用ejs

**Comment by aui** [comment]
希望能够提供测试用例，这样有助于找到核心问题所在。如果 art-template 存在的问题，那 ejs 也会存在

**Comment by DENNIE-HONG** [comment]
测试用例https://github.com/DENNIE-HONG/art-template-demo

**Comment by aui** [comment]
确认是 express-art-template 这个项目的问题，已经修复

**Comment by DENNIE-HONG** [comment]
经过测试，确实解决了内存泄漏问题
