### ISSUE TITLE
each 中使用 tr 标签 在内部嵌套 if  esle 会出现 两个分支同时解析的情况

### ISSUE THREAD

**Issue by hzdjulytech** [aui/art-template#522]
{{each tasks  task i}}
	 {{#str}}  //这里 如果 直接写 <tr>
	        <td>{{task.stageName}}</td>
	        <td>{{task.name}}</td>
	        {{if task._case}}//这个条件可以随便写 比如 true
	        <td> 
	         <span class="lightColor col-xs-1" data-v="{{task._case.lightColor}}"> xx</span>
	         </td>
            <td>{{task._case.aa}}</td>
            <td>{{task._case.bb}}</td>
            <td>1111</td>
            {{else}}
            <td colspan="4">~</td>
            {{/if}}
         {{#etr}} //这里 如果 直接写 </tr>
      {{/each}}

将  {{#str}}    {{#etr}}  换成 tr 标签 会 出现   {{else}} 前后两个部分都输出的情况

**Comment by aui** [comment]
提问之前应当先遵循提问的规范，这里不回答使用问题
