### ISSUE TITLE
匿名数组如何使用each遍历

### ISSUE THREAD

**Issue by wxk0248** [aui/art-template#531]
示例的demo中需要遍历的对象都是list: ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']这样的，如果返回结果是个匿名数组时，即没有前边的list，直接是['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']这样形式，改如何使用

**Comment by aui** [comment]
问题关闭原因，没有遵循 issue 规则：

> 3. 不欢迎询问使用问题，否则直接关闭问题

**Comment by wxk0248** [comment]
关了吧，这个“不欢迎询问使用问题”的规则蛮让人无语的，有这个插件使用中碰到问题的交流平台么

**Comment by aui** [comment]
主要是不欢迎不看文档就提问的人，不是针对你一个
