### ISSUE TITLE
想问下做着 有什么方法可以检测到模板渲染完成吗 想在模板渲染完成后在模板上做一些处理，现在只能用定时器

### ISSUE THREAD

**Issue by peiluojia** [aui/art-template#534]

**Comment by aui** [comment]
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. **标题请简短**，把内容写在 Issue 内容中，否则直接关闭问题
3. **不欢迎询问使用问题，否则直接关闭问题**
