### ISSUE TITLE
4.0版本去掉了template.helper，那么自定义方法怎么写？

### ISSUE THREAD

**Issue by huangwandou** [aui/art-template#535]
4.0版本去掉了template.helper，那么自定义方法怎么写？

**Comment by aui** [comment]
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. **标题请简短**，把内容写在 Issue 内容中，否则直接关闭问题
3. **不欢迎询问使用问题**，否则直接关闭问题
