### ISSUE TITLE
如何用原生语法时间戳转日期

### ISSUE THREAD

**Issue by inputherf** [aui/art-template#537]
网上很多都是用的helper这个方法，但是现在模板已经不在支持。然后就是文档中的例子不够清晰，所以我不能明白为什么不可以
` <td><%= $imports.dateFormat($imports.timestamp(list[i].c)) %></td>`
然后是我注册的js文件
`function timestampToTime(timestamp) {
          var date = new Date(timestamp);//时间戳为10位需*1000，时间戳为13位的话不需乘1000
          Y = date.getFullYear() + '-';
          M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';
          D = date.getDate() + ' ';
          h = date.getHours() + ':';
          m = date.getMinutes() + ':';
          s = date.getSeconds();
          return Y+M+D+h+m+s;
      }
      template.defaults.imports.timestamp = function(value){
        return timestampToTime(value);
      
      };`
这样的后果是一直在报错 **RuntimeError: $imports.timestamp is not a function**。
感觉用模板转时间戳的需求很少，但是现在我们需要，无法很好的转，请问是我理解文档出错了吗？我的格式哪里有问题呢

**Comment by aui** [comment]
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
