### ISSUE TITLE
如何实现只局部渲染新数据，老数据不渲染？

### ISSUE THREAD

**Issue by zgj233** [aui/art-template#541]
@aui 

art-template each 函数有类似于 vue.js 的 v-for 一样的效果吗？
如果data数组append了 一项新的数据，如何只渲染这条新的，并append 到 DOM List 的 尾部？
跪谢作者帮助：）

**Comment by aui** [comment]
不能，这是一个字符串模板引擎

**Comment by doulele** [comment]
this is a test

**Comment by doulele** [comment]
this is a test too

**Comment by doulele** [comment]
地方v
