### ISSUE TITLE
art-template-web在input type=checkbox时有解析bug

### ISSUE THREAD

**Issue by isszz** [aui/art-template#544]
`<input{{ value.status ? ' checked' : ''}} type="checkbox">`
上面这样写会报错
`CompileError: Unexpected token =
   generated: $$out+=value.status="" ?="" 'checked'="" :="" ''`

**Comment by isszz** [comment]
`<input{{ if value.status }} checked="checked"{{ /if }} type="checkbox">`
我试了这样写一样是报错的...
```
{{ if value.status }}
<input checked="checked" type="checkbox">
{{ else }}
<input type="checkbox">
{{ /if }}
```
实在没辙只能改成这样了...

**Comment by aui** [comment]
在默认配置下，是能够正常编译的，如图：
![image](https://user-images.githubusercontent.com/1791748/41834434-db6ef112-7886-11e8-8391-1010492d7034.png)
你应该按照规范提交问题：提供可以重现的 DEMO

**Comment by isszz** [comment]
@aui 我发现好多语法不支持....最近什么>  < 之类的还有就是一个if多个判断...都提示错误,原因是把==,<, >,!=之类的全转义了...
`template-web.js?v=20180610:3 Uncaught Error: J_list_template:3:1
    1| 
    2| {{ if list }}
 >> 3| {{ if (type == 'pay' ||  type == 'all') &amp;&amp; !hideStockTips }}
    4| <div class="c"></div>
    5| <div class="alert alert-info mb10 f14" style="border:0 none;">{{ hideStockTips }}温馨提示：避免库存不足影响其他用户下单，待支付订单有效期为：{{floor(ActivityOrderSrv::EXPIRED_TIME / 60)}}分钟，过期需重新下单。</div>
    6| {{ /if }}

CompileError: Unexpected token ;
   generated: if((type == 'pay' ||  type == 'all') &amp;&amp; !hideStockTips){`

**Comment by isszz** [comment]
我好想发现这个不是art-template的问题
我把模板放在<template></template>里面会把那些符号转义- -...

**Comment by aui** [comment]
在 html 中，`<` 与 `>` 字符默认情况下是会被浏览器转义的，你应该注意这个问题，建议采用文档推荐的方式来存放模板。

**Comment by isszz** [comment]
好吧,了解了...谢谢
