### ISSUE TITLE
输出变量自动添加双引号

### ISSUE THREAD

**Issue by yxl720** [aui/art-template#551]
{{each cateList as item}}
                <tr cate-id='1' fid='0'>
                    <td>
                       
                    </td>
                    <td>{{item._id}}</td>
                    <td>
                        {{item.CateName}}
                    </td>
                   
                    <td class="td-manage">
                        <button class="layui-btn layui-btn layui-btn-xs" onclick="x_admin_show('编辑','./cate/cateedit/{{item._id}}')">编辑</button>
                        <button class="layui-btn layui-btn-warm layui-btn-xs" onclick="x_admin_show('编辑','./cateadd')">添加子栏目</button>
                        <button class="layui-btn-danger layui-btn layui-btn-xs" onclick="member_del(this,'{{item._id}}')" href="javascript:;">删除</button>
                    </td>
                </tr>
                {{/each}}

比如:{{item._id}}  的那个路径会变成'./cate/cateedit/"5b7a5638aecb263f94335d8d"'   自动添加"" 导致路径跳转不了

**Comment by aui** [comment]
请按照规范提交问题。

**Comment by tsurumure** [comment]
环境: koa + mongodb
数据: `response: [{"_id":"5d5662eca1a19c41740ee08a","title":"小标题"}, { .. }]`
模板:
```
<each response as item>
{{ item._id }} - {{ item.title }} 
</each>
```
输出:
"5d5662eca1a19c41740ee08a" - 小标题

我的问题:
`_id` 字段自带双引号，`title` 字段不带双引号，要怎么才能让 `_id` 不自带双引号？
