### ISSUE TITLE
art-template runtime window未定义

### ISSUE THREAD

**Issue by wangzhigang** [aui/art-template#553]
var runtime = Object.create(detectNode ? global : window);

报错 window 未定义

建议安装@fedor/global
var window = require('@fedor/global');
var runtime = Object.create(detectNode ? global : window); 修复此问题

**Comment by aui** [comment]
什么情况会报错？

**Comment by 997282173** [comment]
重新 npm install 以后就一直报这个错误

**Comment by aui** [comment]
给一下有助于重现的信息吧，例如 nodejs 和 npm 版本

**Comment by lnyielea** [comment]
ERROR in   Error: /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:769
  var runtime = Object.create(detectNode ? global : window);
                                                    ^
  ReferenceError: window is not defined

  - index.art:769 Object.<anonymous>
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:769:51

  - index.art:863 Object../node_modules/art-template/lib/compile/runtime.js
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:863:30

  - index.art:684 __webpack_require__
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:684:30

  - index.art:61 fn
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:61:20

  - index.art:877 Object../node_modules/art-template/lib/runtime.js
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:877:18

  - index.art:684 __webpack_require__
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:684:30

  - index.art:61 fn
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:61:20

  - index.art:901 Object../node_modules/html-webpack-plugin/lib/loader.js!./src/pages/index/index.art
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:901:16

  - index.art:684 __webpack_require__
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:684:30

  - index.art:751
    /Users/linyi/work/company/sqjh/test/src/pages/index/index.art:751:114
node v8.2.1 v10.1.0 v10.10.0都会这样。npm 5

**Comment by zhihuilai** [comment]
我在 HtmlWebpackPlugin 中使用 art-template，process.toString 是 [object object]，但在 node 中直接执行 process.toString() 是 [object process]，不确定是不是 HtmlWebpackPlugin 应该背锅，有可能是其它代码引起的，但可以确认 detect-node 在某些情况下会判断错误。
