### ISSUE TITLE
循环列表再嵌套循环，会经常读取不到嵌套循环的数据？怎么解？

### ISSUE THREAD

**Issue by yongheng798** [aui/art-template#554]
经常有列表，列表循环后还会带有循环的列表数据，可是一旦读取到嵌套循环的数据就会卡死或者崩溃，这是怎么回事呢？
而且嵌套循环再循环的性能很慢真的很慢很慢啊？
求大神解读
如循环下列的数据，我的前端代码：
`<% if(images_address!=''){%>
	<div class="container_inner">
		<div class="detail-contents">
			<h3 class="title"><%=images_title%></h3>
			<div class="detail-content" id="d_address_data">
				<% for (i = 0; i < images_address.length; i++) { %>
				<div class="d-sex-imgs">
					<h3><%=images_address[i]['image_abstract']%></h3>
					<p class="bdimg"><img rel="lazy" src="" data-url="<%=images_address[i]['_images']%>"></p>
					<%if(images_address[i]['image_goods']!=''){%>
					<% var goods_list = images_address[i]['image_goods_b']; %>
					<ul class="d-product">
						<%for(i=0; i < goods_list.length; i++){%>
						<li><a href="<%=goods_list[i].url %>">
							<p class="img"><img rel="lazy" src="" data-url="<%=goods_list[i].image %>"></p>
							<h3><%=goods_list[i].title %></h3>
							<p class="price"><i><%=goods_list[i].price %></i></p>
						</a>
						</li>
						<%}%>
					</ul>
					<%}%>
				</div>
				<%}%>
				<%if(images_count>5){%>
				<div class="more-loading none"></div>
				<div class="more-imgs">
					<a href="javascript:" class="load-more-imgs"><span class="txt">查看全部</span>(<%=images_count%>)</a>
				</div>
				<%}%>
			</div>
		</div>
	</div>
	<%}%>`

`{
  "code": 200,
  "datas": {
    "images_title": "场地",
    "images_count": "8",
    "images_address": [
      {
        "image_id": "384",
        "image_name": "05467832391625738.jpg",
        "image_abstract": "555",
        "image_goods": "a:2:{i:0;a:4:{s:3:\"url\";s:74:\"http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970\";s:5:\"image\";s:83:\"http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg\";s:5:\"price\";s:5:\"55.00\";s:5:\"title\";s:70:\"标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）\";}i:1;a:4:{s:3:\"url\";s:82:\"http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970\";s:5:\"image\";s:83:\"http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg\";s:5:\"price\";s:5:\"55.00\";s:5:\"title\";s:74:\"标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）\";}}",
        "image_store": null,
        "image_width": "640",
        "image_height": "480",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832391625738_max.jpg",
        "image_goods_b": [
          {
            "url": "http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970",
            "image": "http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg",
            "price": "55.00",
            "title": "标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）"
          },
          {
            "url": "http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970",
            "image": "http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg",
            "price": "55.00",
            "title": "标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）"
          }
        ]
      },
      {
        "image_id": "383",
        "image_name": "05467832390090509.jpg",
        "image_abstract": "4、我想记住你的脸。",
        "image_goods": "",
        "image_store": null,
        "image_width": "640",
        "image_height": "450",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832390090509_max.jpg"
      },
      {
        "image_id": "382",
        "image_name": "05467832393148078.jpg",
        "image_abstract": "考研智慧和创意的时刻到了！一起合作用手边的颜料笔刷完成公司的Logo巨画吧！更有高端航拍定格合影瞬间！",
        "image_goods": "",
        "image_store": null,
        "image_width": "640",
        "image_height": "427",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832393148078_max.jpg"
      },
      {
        "image_id": "381",
        "image_name": "05467832388611861.jpg",
        "image_abstract": "项目名称：限时通讯。参与者在全程禁止使用手机等现代工具，参与者每天会得到规定的五分钟与外界电话交流以及邮件沟通。参与者选择任意一个人通话并且可三封邮件。\r\n所有成员完成限时通讯之后，全体讨论分享。该环节可与任意成员联系，观察参与者的价值观；也可设计为仅与同事联系，观察同事关系。",
        "image_goods": "",
        "image_store": null,
        "image_width": "640",
        "image_height": "426",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832388611861_max.jpg"
      },
      {
        "image_id": "380",
        "image_name": "05467166861742975.png",
        "image_abstract": "4、我想记住你的脸。\r\n考研智慧和创意的时刻到了！\r\n一起合作用手边的颜料笔刷完成公司的Logo巨画吧！更有高端航拍定格合影瞬间！",
        "image_goods": "",
        "image_store": null,
        "image_width": "96",
        "image_height": "96",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467166861742975_max.png"
      }
    ],
    "images_address_more": [
      {
        "image_id": "382",
        "image_name": "05467832393148078.jpg",
        "image_abstract": "考研智慧和创意的时刻到了！一起合作用手边的颜料笔刷完成公司的Logo巨画吧！更有高端航拍定格合影瞬间！",
        "image_goods": "",
        "image_store": null,
        "image_width": "640",
        "image_height": "427",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832393148078_max.jpg"
      },
      {
        "image_id": "383",
        "image_name": "05467832390090509.jpg",
        "image_abstract": "4、我想记住你的脸。",
        "image_goods": "",
        "image_store": null,
        "image_width": "640",
        "image_height": "450",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832390090509_max.jpg"
      },
      {
        "image_id": "384",
        "image_name": "05467832391625738.jpg",
        "image_abstract": "555",
        "image_goods": "a:2:{i:0;a:4:{s:3:\"url\";s:74:\"http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970\";s:5:\"image\";s:83:\"http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg\";s:5:\"price\";s:5:\"55.00\";s:5:\"title\";s:70:\"标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）\";}i:1;a:4:{s:3:\"url\";s:82:\"http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970\";s:5:\"image\";s:83:\"http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg\";s:5:\"price\";s:5:\"55.00\";s:5:\"title\";s:74:\"标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）\";}}",
        "image_store": null,
        "image_width": "640",
        "image_height": "480",
        "image_picture_id": "108",
        "image_path": "3",
        "image_sort": null,
        "_images": "http://local.qbermall.cn/data/upload/cms/article/3/05467832391625738_max.jpg",
        "image_goods_b": [
          {
            "url": "http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970",
            "image": "http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg",
            "price": "55.00",
            "title": "标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）"
          },
          {
            "url": "http://local.qbermall.cn/shop/index.php?act=goods&op=index&goods_id=101970",
            "image": "http://local.qbermall.cn/data/upload/shop/store/goods/1/1_05320182325677528_240.jpg",
            "price": "55.00",
            "title": "标准尺寸规格舞台搭建 （含地毯 &人工安装和拆卸 ）"
          }
        ]
      }
    ]
  }
}`

**Comment by aui** [comment]
你提问之前应该看到了输入框提示文本：

``
1. 请附带可以 **直接** 重现的 Demo，可以是压缩包、仓库、或者使用在线运行服务，否则直接关闭问题
2. 标题请简短，把内容写在 Issue 内容中，否则直接关闭问题
3. 不欢迎询问使用问题，否则直接关闭问题
``

如果是提交 BUG，第一条规则很重要。
