### ISSUE TITLE
希望增加大于小于和大于等于小于等于的判断

### ISSUE THREAD

**Issue by kangaroo711** [aui/art-template#555]
如题,需求用到太多大于小于的判断了,希望能更新,期待

**Comment by kangaroo711** [comment]
测试了好像undefined和null可以哈哈

**Comment by aui** [comment]
你的问题是什么？

**Comment by kangaroo711** [comment]
> 你的问题是什么？

像这个,
{if $value.state==2||$value.state==3||$value.state==4||$value.state==5||$value.state==6||$value.state==7}}{{/if}}
如果有{{if $value.state>=2}}那样就方便多了

**Comment by aui** [comment]
你给的例子本身就支持。如果不懂的地方可以看文档。

**Comment by kangaroo711** [comment]
> 你给的例子本身就支持。如果不懂的地方可以看文档，issues 不提供使用问题支持，如果是 BUG 按照规范提交问题。

并不支持>=和<=或者>和<!  不是bug,是建议新增这种功能;.

**Comment by Lynn-cc** [comment]
Ps、文档的条件判断的示例里，没有大小比较条件语法。
