### ISSUE TITLE
浏览器中使用的版本下载链接失效了

### ISSUE THREAD

**Issue by iamziyue** [aui/art-template#556]
文档：https://aui.github.io/art-template/zh-cn/docs/installation.html
下载链接：https://raw.githubusercontent.com/aui/art-template/master/lib/template-web.js
现在404了，在仓库中也没找到这个文件。

**Comment by aui** [comment]
文档已经修复。新的下载地址：<https://unpkg.com/art-template/lib/template-web.js>
