### ISSUE TITLE
artTemplate 解析复杂对象属性无效

### ISSUE THREAD

**Issue by a1586256143** [aui/art-template#559]
var item = {
       list : [{
              name : '111' ,  
               info : { desc : '描述信息' }
       }]
};
模板渲染如下
{{each item eachItem index}}
     {{ eachItem.info.desc }}
{{/each}}

模板报错如下

TemplateError: Cannot read property 'name' of undefined

**Comment by aui** [comment]
模板写错了：

```
{{each list eachItem index}}
{{ eachItem.info.desc }}
{{/each}}
```

**Comment by a1586256143** [comment]
模板没有写错，是一样的

**Comment by aui** [comment]
你应该提供 demo，这样才能有效的解决问题
