### ISSUE TITLE
辅助方法怎么才不会直接输出html

### ISSUE THREAD

**Issue by billwing** [aui/art-template#56]
需求如下所示：

```
// ArtTemplate compareZero
ArtTemplate.helper('compareZero', function (range) {
    var cnt;
    if(range > 0) {
        cnt = '<span class="red">' + range + '</span>';
    } else if(range < 0) {
        cnt = '<span class="green">' + range + '</span>';
    } else {
        cnt = range;
    }
    return cnt;
});
```

**Comment by johnjackson** [comment]
我的代码如下，但还是输出了HTML, 请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d">'+number+'</span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
我的代码如下，但还是输出了HTML, 请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d">'+number+'</span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
我的代码如下，但还是输出了HTML, 请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d">'+number+'</span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
我的代码如下，但还是输出了HTML, 请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d">'+number+'</span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
我的代码如下，但还是输出了HTML, 请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d">'+number+'</span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
我的代码如下，但还是直接输出了HTML,请问这是为什么？
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('<span class="star active d"></span>');
    }
    return html;
});

**Comment by johnjackson** [comment]
template.helper('number_to_star', function(number) {
    var html = '';
    for(var i = 0; i < number; i++) {
        html += template.utils.$escape('&lt;span class="star active d"&gt;&lt;/span&gt;');// 编码;
    }
    return html;
});

**Comment by johnjackson** [comment]
{{#value}} ,即不编码输出
