### ISSUE TITLE
抱歉，这个需求有点怪异

### ISSUE THREAD

**Issue by githublaohu** [aui/art-template#566]
想实现一个简单的 mybatis，模板方面想使用art-template。有一些地方无法满足。 
var user ={userId ：1 , userName ： ”art“}
<script>
 update table set userName ={{}userName} where use_id = {{userId}}
</script>

 得到下面的字符串 update table set userName =? where use_id = ?
同时得到 [1 , art]

只是一个想法而已。不要怒对。

**Comment by aui** [comment]
提问之前是否可以组织下你的问题？
