### ISSUE TITLE
结合express，当jquery ajax返回后端数据后，把数据动态地渲染到模板的时候对象为空字符串

### ISSUE THREAD

**Issue by 1075551055** [aui/art-template#567]
**前提：**
node服务端端也使用了art-template，当在前端页面ajax请求数据回来后，调用template()组装出来的对象只有空字符串，何解？使用方法不对？

**代码：**
$('#userForm').submit(function (e) {
        e.preventDefault();
        var url = '/users';
        $.ajax(url, {
            type: 'post',
            headers: {
              Accept: 'text/html'
            },
            data: $('#userForm').serialize(),
            success: function (data) {
                var data = {
                    title: '基本例子',
                    isAdmin: true,
                    list: ['文艺', '博客', '摄影', '电影', '民谣', '旅行', '吉他']
                };
                var html = template('test', data);
                $('#errorDiv').html(html);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                console.log(errorThrown);
            }
        });

template('test', data)组装出来的数据为空字符串

**Comment by aui** [comment]
问题关闭原因：没有遵循 issues 模板规范
