### ISSUE TITLE
index.d.ts 有个拼写错误

### ISSUE THREAD

**Issue by rpdg** [aui/art-template#568]
![tim 20181221100034](https://user-images.githubusercontent.com/1169162/50320471-7bb6d380-0507-11e9-8b2d-3fe16e898050.png)

excape  -> escape

**Comment by aui** [comment]
谢谢反馈，可以帮提一个 PR 吗？:-)

**Comment by wheasy** [comment]
@aui  git仓库上虽然是escape，但是npm的包里还是excape
