### ISSUE TITLE
在模板内使用easyui的渲染不起作用

### ISSUE THREAD

**Issue by pop709895** [aui/art-template#580]
<script type="text/html" id="ytea">
	<div id="calculatiton_roadmap"  class="easyui-tabs" data-options="fit:true">
	{{each data data index}}
		<div title="{{data.planName}}" style="padding:5px;display: block;">
			<table class="body_table" style="width:99.9%;margin-left:1px;margin- 
               right:1px;font-size: 14px;" cellpadding="3" cellspacing="1">
			
				<tr style="line-height:25px;">
				<td style="background-color: #EEEEEE;">{{data.planName}}</td>
                              </tr>
                      </table>
             <div>
       {{/each}}
</div>
<script>
那像这样与easyui或者其他的进行交互的操作能改进么？

**Comment by aui** [comment]
提 issue 之前，你应当可以看到输入框中的规则，请遵循既定的规则我们再来讨论问题。
