### ISSUE TITLE
ReferenceError: imports is not defined

### ISSUE THREAD

**Issue by nokelong** [aui/art-template#583]
代码 ：
**template.defaults.imports**('isValidMobile', function(mobile) {
    if(/\*+/.test(mobile)){
          return false;
    }
    return true;
});

Template.defaults.imports 这个地方之前用的是**template.helpers,**版本升级到4.13.2。
版本：
 "art-template": "^4.13.2",
  "art-template-loader": "^1.4.3",
使用的是：lib/template-web.js

**Comment by aui** [comment]
请按规则提交问题
