### ISSUE TITLE
文档能不能不要写的像一坨屎

### ISSUE THREAD

**Issue by codisan** [aui/art-template#586]
在浏览器中使用时，传递的是 script 标签的ID， 而不是真正的模板内容
template('temp_id', {user: {name: 'tom'}});

这个设计本身就很傻逼了，完了文档他妈还没说明

这样的东西居然能聚齐8000+的 star，真的是见鬼了！

**Comment by aui** [comment]
大爷，请看这里，还给您提供了中文文档 <https://aui.github.io/art-template/zh-cn/docs/api.html>

**Comment by hlipeter** [comment]
@codisan @aui I'm agree with 大爷，Your documentation is terrible，写的过于简单，爬去看源码，俺太南了......

「看了标题过来顶一下！」
