### ISSUE TITLE
过滤器无法调用外部的函数？

### ISSUE THREAD

**Issue by suifeng50124** [aui/art-template#592]
在模板里 ，我定义了一个过滤器，返回的是一个外部的utils函数，但是在部分设备上无法读取到

**Comment by suifeng50124** [comment]
![image](https://user-images.githubusercontent.com/48434203/59898686-81dd2c80-9424-11e9-9133-5efda1588645.png)

**Comment by suifeng50124** [comment]
![image](https://user-images.githubusercontent.com/48434203/59898723-a5a07280-9424-11e9-8f73-7937303fe1ff.png)
![image](https://user-images.githubusercontent.com/48434203/59898758-ce286c80-9424-11e9-8913-74ba5940d990.png)

**Comment by aui** [comment]
请按照issues模板提交问题
