### ISSUE TITLE
render函数浏览器端出错，无法进行渲染

### ISSUE THREAD

**Issue by zhangfisher** [aui/art-template#598]
在Nodejs下可以正常运行

template.render("{{a}}",{a:1})

但在浏览器端
Vue-cli工程
import artTemplate from "art-template"
同样的代码
template.render("{{a}}",{a:1})
出错：
webpack打包时出错
require.extensions is not supported by webpack. Use a loader instead.
在浏览器运行时出错:
Cannot set property '.art' of undefined

**Comment by aui** [comment]
可以提供一份 demo 否？

**Comment by zhangfisher** [comment]
demo没有问题，经过修改后没有问题了

import artTemplate from "art-template/lib/template-web"
以下导入就有问题
import artTemplate from "art-template"
应该是模块识别的问题
