### ISSUE TITLE
渲染带标签的内容的时候，如果标签不完整，就会导致页面错位

### ISSUE THREAD

**Issue by yybb8007** [aui/art-template#608]
![image](https://user-images.githubusercontent.com/23164614/68102998-1053d580-ff10-11e9-9865-72de9e28739f.png)

有一段内容是【嘿嘿嘿<img src="asdjflasdjflsdfkjasldkfj】,然后就会导致后面的列表错位

**Comment by yybb8007** [comment]
这种是不是可以不要介些成标签，他会一只找到下一个匹配的双引号

**Comment by aui** [comment]
你的问题是什么？这是 BUG 还是特性？

**Comment by aui** [comment]
这是 HTML 的特性，标签没有闭合会引起各种各样的问题
