### ISSUE TITLE
如何插值为html标签的属性，而不仅是插值为内容？

### ISSUE THREAD

**Issue by WyxXu** [aui/art-template#652]

**Comment by 704585069** [comment]
这里是付剑伟您的来信已收到我会尽快给您回复

**Comment by aui** [comment]
> _No description provided._

请阅读文档

**Comment by aui** [comment]
> 这里是付剑伟您的来信已收到我会尽快给您回复

请不要回复无关内容

**Comment by WyxXu** [comment]
> > _No description provided._
> 
> 请阅读文档

文档演示中没有在标签内插值的示例，
vscode的插件，写在<>内的花括号也是不高亮的。
 让我误以为只能插值为元素的内容，不能在插值属性和属性值。
经过尝试，是可以的。
